#pragma once
#include<string>

#include<Error.h>

namespace db::v0_0_1 {
  constexpr std::string_view CURRENT_VERSION = "0.0.1";
  struct Column {
    std::string_view columnName;
    std::string_view columnType;
    bool nullable;
    bool autoIncrement;

    constexpr Column(): Column("", "") {}
    constexpr Column(std::string_view columnName, std::string_view columnType, bool nullable = false, bool autoIncrement = false): 
      columnName(columnName), columnType(columnType), nullable(nullable), autoIncrement(autoIncrement) {}
    
    constexpr Column & setColumnName(std::string_view name) {this->columnName = name; return *this;}
    constexpr Column & setColumnType(std::string_view type) {this->columnType = type; return *this;}
    constexpr Column & setNullable(bool nullable) {this->nullable = nullable; return *this;}
    constexpr Column & setAutoIncrement(bool autoIncrement) {this->autoIncrement = autoIncrement; return *this;}

    constexpr auto operator<=>(Column const& o) const = default;
  };

  constexpr std::string_view SQL_DROP_SCHEMA = "drop database if exists `{}`";
  constexpr std::string_view SQL_CREATE_SCHEMA = "create schema `{}`";
  constexpr std::string_view SQL_CREATE_TABLE = "create table `{}`.`{}` ({})";
  constexpr std::string_view SQL_CREATE_COLUMN = "`{}` {} {} null {}";
  constexpr std::string_view SQL_DEFINE_PRIMARY_KEY = "primary key (`{}`)";
  constexpr std::string_view SQL_INSERT = "insert into `{}`.`{}` ({}) values {}";

  constexpr std::string_view SQL_INT = "int";
  constexpr std::string_view SQL_SMALLSTRING = "varchar(45)";
  constexpr std::string_view SQL_LARGESTRING = "varchar(512)";
  constexpr std::string_view SQL_TEXT = "text";
  constexpr std::string_view SQL_BOOL = "tinyint";
  constexpr std::string_view SQL_DATETIME = "datetime";
  constexpr std::string_view SQL_BLOB = "blob";
  constexpr std::string_view SQL_DOUBLE = "double";

  constexpr std::string_view DB_GENERAL = "GENERAL";
  constexpr std::string_view DB_DATA = "DATA";
  constexpr std::string_view DB_STATE = "STATE";
  constexpr std::string_view DB_RESOURCE = "RESOURCE";

  constexpr std::string_view TABLE_META = "META";
  constexpr Column           COLUMN_META_VERSION{"VERSION", SQL_SMALLSTRING};
  constexpr Column           COLUMN_META_PROTECTED{"PROTECTED", SQL_BOOL};

  constexpr std::string_view TABLE_IMAGE_RESOURCE = "IMAGE_RESOURCE";
  constexpr Column           COLUMN_IMAGERESOURCE_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_IMAGERESOURCE_PACK_ID{"PACK_ID", SQL_INT};
  constexpr Column           COLUMN_IMAGERESOURCE_KEY{"KEY", SQL_SMALLSTRING};
  constexpr Column           COLUMN_IMAGERESOURCE_TYPE{"TYPE", SQL_SMALLSTRING};
  constexpr Column           COLUMN_IMAGERESOURCE_ARMYCOLOR{"ARMYCOLOR", SQL_SMALLSTRING, true};
  constexpr Column           COLUMN_IMAGERESOURCE_ORIENTATION{"ORIENTATION", SQL_INT, true};
  constexpr Column           COLUMN_IMAGERESOURCE_VARIANT{"VARIANT", SQL_SMALLSTRING, true};
  constexpr Column           COLUMN_IMAGERESOURCE_ORDER{"ORDER", SQL_INT, true};
  constexpr Column           COLUMN_IMAGERESOURCE_SMALLIMAGE{"SMALLIMAGE", SQL_LARGESTRING, true};
  constexpr Column           COLUMN_IMAGERESOURCE_LARGEIMAGE{"LARGEIMAGE", SQL_LARGESTRING, true};
  constexpr Column           COLUMN_IMAGERESOURCE_SMALLIMAGEBLOB{"SMALLIMAGEBLOB", SQL_BLOB, true};
  constexpr Column           COLUMN_IMAGERESOURCE_LARGEIMAGEBLOB{"LARGEIMAGEBLOB", SQL_BLOB, true};
  constexpr std::string_view TABLE_TEXT_RESOURCE = "TEXT_RESOURCE";
  constexpr Column           COLUMN_TEXTRESOURCE_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_TEXTRESOURCE_PACK_ID{"PACK_ID", SQL_INT};
  constexpr Column           COLUMN_TEXTRESOURCE_KEY{"KEY", SQL_SMALLSTRING};
  constexpr Column           COLUMN_TEXTRESOURCE_TYPE{"TYPE", SQL_SMALLSTRING};
  constexpr Column           COLUMN_TEXTRESOURCE_SHORTNAME{"SHORTNAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_TEXTRESOURCE_LONGNAME{"LONGNAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_TEXTRESOURCE_DESCRIPTION{"DESCRIPTION", SQL_LARGESTRING};
  constexpr Column           COLUMN_TEXTRESOURCE_LANGUAGE{"LANGUAGE", SQL_SMALLSTRING, true};
  constexpr std::string_view TABLE_PACK = "PACK";
  constexpr Column           COLUMN_RESOURCEPACK_PACK_ID{"PACK_ID", SQL_INT, false, true};
  constexpr Column           COLUMN_RESOURCEPACK_NAME{"NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_RESOURCEPACK_VERSION{"VERSION", SQL_SMALLSTRING};
  constexpr Column           COLUMN_RESOURCEPACK_CREATED{"CREATED", SQL_DATETIME};
  constexpr Column           COLUMN_RESOURCEPACK_EXPIRED{"EXPIRED", SQL_DATETIME, true};
  constexpr Column           COLUMN_RESOURCEPACK_PROTOCOL{"PROTOCOL", SQL_INT, true};

  constexpr std::string_view TABLE_STATE_GAME = "GAME";
  constexpr Column           COLUMN_STATE_GAME_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_STATE_GAME_DAY{"DAY", SQL_INT};
  constexpr Column           COLUMN_STATE_GAME_PLAYER_TURN{"PLAYER_TURN", SQL_INT};
  constexpr Column           COLUMN_STATE_GAME_VARIANT{"VARIANT", SQL_SMALLSTRING};
  constexpr Column           COLUMN_STATE_GAME_VARIANTSTART{"VARIANTSTART", SQL_SMALLSTRING, true};
  constexpr Column           COLUMN_STATE_GAME_ACTIVE{"ACTIVE", SQL_BOOL};
  constexpr Column           COLUMN_STATE_GAME_HASH{"HASH", SQL_INT};
  constexpr Column           COLUMN_STATE_GAME_LANGUAGE{"LANGUAGE", SQL_SMALLSTRING, true};
  constexpr std::string_view TABLE_STATE_GAME_PLAYERORDER = "GAME_PLAYERORDER_REFERENCE";
  constexpr Column           COLUMN_STATE_GAME_PLAYERORDER_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_STATE_GAME_PLAYERORDER_GAME_ID{"GAME_ID", SQL_INT};
  constexpr Column           COLUMN_STATE_GAME_PLAYERORDER_PLAYER{"PLAYER", SQL_INT};
  constexpr Column           COLUMN_STATE_GAME_PLAYERORDER_ORDER{"ORDER", SQL_INT};
  constexpr std::string_view TABLE_STATE_PLAYER = "PLAYER";
  constexpr Column           COLUMN_STATE_PLAYER_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_STATE_PLAYER_GAME_ID{"GAME_ID", SQL_INT};
  constexpr Column           COLUMN_STATE_PLAYER_USER{"USER", SQL_INT};
  constexpr Column           COLUMN_STATE_PLAYER_COMMANDER_NAME{"COMMANDER_NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_STATE_PLAYER_FUNDS{"FUNDS", SQL_INT};
  constexpr Column           COLUMN_STATE_PLAYER_POWER_CHARGE{"POWER_CHARGE", SQL_INT};
  constexpr Column           COLUMN_STATE_PLAYER_ARMY_COLOR{"ARMY_COLOR", SQL_SMALLSTRING};
  constexpr Column           COLUMN_STATE_PLAYER_ALIVE{"ALIVE", SQL_BOOL};
  constexpr Column           COLUMN_STATE_PLAYER_TOTAL_POWER_USES{"TOTAL_POWER_USES", SQL_INT};
  constexpr Column           COLUMN_STATE_PLAYER_UNIT_FACING{"UNIT_FACING", SQL_INT};
  constexpr Column           COLUMN_STATE_PLAYER_PLAYER_TYPE{"PLAYER_TYPE", SQL_SMALLSTRING};
  constexpr Column           COLUMN_STATE_PLAYER_TEAM{"TEAM", SQL_SMALLSTRING, true};
  constexpr Column           COLUMN_STATE_PLAYER_POWER_ACTIVE{"POWER_ACTIVE", SQL_SMALLSTRING, true};
  constexpr Column           COLUMN_STATE_PLAYER_POWER_ACTIVE_DAY{"POWER_ACTIVE_DAY", SQL_INT, true};
  constexpr Column           COLUMN_STATE_PLAYER_INCOME_MULTIPLIER{"INCOME_MULTIPLIER", SQL_INT, true};
  constexpr Column           COLUMN_STATE_PLAYER_CO_METER_MULTIPLIER{"CO_METER_MULTIPLIER", SQL_INT, true};
  constexpr std::string_view TABLE_STATE_PLAYER_BANNEDUNITS = "PLAYER_BANNEDUNITS_REFERENCE";
  constexpr Column           COLUMN_STATE_PLAYER_BANNEDUNITS_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_STATE_PLAYER_BANNEDUNITS_GAME_ID{"GAME_ID", SQL_INT};
  constexpr Column           COLUMN_STATE_PLAYER_BANNEDUNITS_PLAYER_ID{"PLAYER_ID", SQL_INT};
  constexpr Column           COLUMN_STATE_PLAYER_BANNEDUNITS_UNIT_NAME{"UNIT_NAME", SQL_SMALLSTRING};
  constexpr std::string_view TABLE_STATE_UNIT = "UNIT";
  constexpr Column           COLUMN_STATE_UNIT_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_STATE_UNIT_GAME_ID{"GAME_ID", SQL_INT};
  constexpr Column           COLUMN_STATE_UNIT_X{"X", SQL_INT};
  constexpr Column           COLUMN_STATE_UNIT_Y{"Y", SQL_INT};
  constexpr Column           COLUMN_STATE_UNIT_NAME{"NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_STATE_UNIT_AMMO{"AMMO", SQL_INT};
  constexpr Column           COLUMN_STATE_UNIT_FUEL{"FUEL", SQL_INT};
  constexpr Column           COLUMN_STATE_UNIT_ACTIVE{"ACTIVE", SQL_BOOL};
  constexpr Column           COLUMN_STATE_UNIT_STUNNED{"STUNNED", SQL_INT, true};
  constexpr Column           COLUMN_STATE_UNIT_OWNER{"OWNER", SQL_INT, true};
  constexpr Column           COLUMN_STATE_UNIT_HIT_POINTS{"HIT_POINTS", SQL_INT};
  constexpr Column           COLUMN_STATE_UNIT_STEALTHED{"STEALTHED", SQL_BOOL, true};
  constexpr Column           COLUMN_STATE_UNIT_CURRENT_GOOD_LUCK{"CURRENT_GOOD_LUCK", SQL_DOUBLE};
  constexpr Column           COLUMN_STATE_UNIT_CURRENT_BAD_LUCK{"CURRENT_BAD_LUCK", SQL_DOUBLE};
  constexpr std::string_view TABLE_STATE_UNIT_TRANSPORT = "UNIT_TRANSPORT_REFERENCE";
  constexpr Column           COLUMN_STATE_UNIT_TRANSPORT_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_STATE_UNIT_TRANSPORT_GAME_ID{"GAME_ID", SQL_INT};
  constexpr Column           COLUMN_STATE_UNIT_TRANSPORT_TRANSPORT_ID{"TRANSPORT_ID", SQL_INT};
  constexpr Column           COLUMN_STATE_UNIT_TRANSPORT_UNIT_ID{"UNIT_ID", SQL_INT};
  constexpr Column           COLUMN_STATE_UNIT_TRANSPORT_ORDER{"ORDER", SQL_INT};
  constexpr std::string_view TABLE_STATE_TERRAIN = "TERRAIN";
  constexpr Column           COLUMN_STATE_TERRAIN_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_STATE_TERRAIN_GAME_ID{"GAME_ID", SQL_INT};
  constexpr Column           COLUMN_STATE_TERRAIN_X{"X", SQL_INT};
  constexpr Column           COLUMN_STATE_TERRAIN_Y{"Y", SQL_INT};
  constexpr Column           COLUMN_STATE_TERRAIN_NAME{"NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_STATE_TERRAIN_ORIENTATION{"ORIENTATION", SQL_INT, true};
  constexpr Column           COLUMN_STATE_TERRAIN_CAPTURE_POINTS{"CAPTURE_POINTS", SQL_INT, true};
  constexpr Column           COLUMN_STATE_TERRAIN_ACTIVATION_COUNT{"ACTIVATION_COUNT", SQL_INT, true};
  constexpr Column           COLUMN_STATE_TERRAIN_OWNER{"OWNER", SQL_INT, true};
  constexpr Column           COLUMN_STATE_TERRAIN_HIT_POINTS{"HIT_POINTS", SQL_INT, true};
  constexpr Column           COLUMN_STATE_TERRAIN_STEALTHED{"STEALTHED", SQL_BOOL, true};
  constexpr Column           COLUMN_STATE_TERRAIN_CURRENT_GOOD_LUCK{"CURRENT_GOOD_LUCK", SQL_DOUBLE};
  constexpr Column           COLUMN_STATE_TERRAIN_CURRENT_BAD_LUCK{"CURRENT_BAD_LUCK", SQL_DOUBLE};
  constexpr std::string_view TABLE_STATE_SETTINGS = "SETTINGS";
  constexpr Column           COLUMN_STATE_SETTINGS_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_STATE_SETTINGS_GAME_ID{"GAME_ID", SQL_INT};
  constexpr Column           COLUMN_STATE_SETTINGS_STARTING_FUNDS{"STARTING_FUNDS", SQL_INT};
  constexpr Column           COLUMN_STATE_SETTINGS_INCOME_MULTIPLIER{"INCOME_MULTIPLIER", SQL_INT};
  constexpr Column           COLUMN_STATE_SETTINGS_FOG_OF_WAR{"FOG_OF_WAR", SQL_BOOL};
  constexpr Column           COLUMN_STATE_SETTINGS_CO_POWERS{"CO_POWERS", SQL_BOOL};
  constexpr Column           COLUMN_STATE_SETTINGS_TEAMS{"TEAMS", SQL_BOOL};
  constexpr Column           COLUMN_STATE_SETTINGS_MOD_ID{"MOD_ID", SQL_INT};
  constexpr Column           COLUMN_STATE_SETTINGS_CO_METER_SIZE{"CO_METER_SIZE", SQL_INT};
  constexpr Column           COLUMN_STATE_SETTINGS_CO_METER_MULTIPLIER{"CO_METER_MULTIPLIER", SQL_INT};
  constexpr Column           COLUMN_STATE_SETTINGS_UNIT_LIMIT{"UNIT_LIMIT", SQL_INT, true};
  constexpr Column           COLUMN_STATE_SETTINGS_CAPTURE_LIMIT{"CAPTURE_LIMIT", SQL_INT, true};
  constexpr Column           COLUMN_STATE_SETTINGS_DAY_LIMIT{"DAY_LIMIT", SQL_INT, true};
  constexpr std::string_view TABLE_STATE_SETTINGS_VARIANT = "SETTINGS_VARIANT_REFERENCE";
  constexpr Column           COLUMN_STATE_SETTINGS_VARIANT_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_STATE_SETTINGS_VARIANT_GAME_ID{"GAME_ID", SQL_INT};
  constexpr Column           COLUMN_STATE_SETTINGS_VARIANT_VARIANT{"VARIANT", SQL_SMALLSTRING};
  constexpr Column           COLUMN_STATE_SETTINGS_VARIANT_WEIGHT{"WEIGHT", SQL_INT};

  constexpr std::string_view TABLE_DATA_MOD = "MOD";
  constexpr Column           COLUMN_DATA_MOD_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_DATA_MOD_NAME{"NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_MOD_VERSION{"VERSION", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_MOD_EXPIRED{"EXPIRED", SQL_DATETIME, true};
  constexpr std::string_view TABLE_DATA_MOD_DEFAULTPACK = "MOD_DEFAULTPACK_REFERENCE";
  constexpr Column           COLUMN_DATA_MOD_DEFAULTPACK_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_DATA_MOD_DEFAULTPACK_MOD_ID{"MOD_ID", SQL_INT};
  constexpr Column           COLUMN_DATA_MOD_DEFAULTPACK_NAME{"NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_MOD_DEFAULTPACK_ORDER{"ORDER", SQL_INT};
  constexpr Column           COLUMN_DATA_MOD_DEFAULTPACK_VERSION{"VERSION", SQL_SMALLSTRING, true};

  constexpr std::string_view TABLE_DATA_UNIT = "UNIT_TYPE";
  constexpr Column           COLUMN_DATA_UNIT_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_DATA_UNIT_MOD_ID{"MOD_ID", SQL_INT};
  constexpr Column           COLUMN_DATA_UNIT_NAME{"NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_UNIT_COST{"COST", SQL_INT};
  constexpr Column           COLUMN_DATA_UNIT_MAXFUEL{"MAXFUEL", SQL_INT};
  constexpr Column           COLUMN_DATA_UNIT_MAXAMMO{"MAXAMMO", SQL_INT};
  constexpr Column           COLUMN_DATA_UNIT_VISIONRANGE{"VISIONRANGE", SQL_INT};
  constexpr Column           COLUMN_DATA_UNIT_MOVEMENTCLASS{"MOVEMENTCLASS", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_UNIT_MOVEMENTRANGE{"MOVEMENTRANGE", SQL_INT};
  constexpr Column           COLUMN_DATA_UNIT_FUELPERDAY{"FUELPERDAY", SQL_INT, true};
  constexpr Column           COLUMN_DATA_UNIT_FUELPERDAYSTEALTH{"FUELPERDAYSTEALTH", SQL_INT, true};
  constexpr Column           COLUMN_DATA_UNIT_SUPPLYREPAIR{"SUPPLYREPAIR", SQL_INT, true};
  constexpr Column           COLUMN_DATA_UNIT_TRANSPORTCAPACITY{"TRANSPORTCAPACITY", SQL_INT, true};
  constexpr Column           COLUMN_DATA_UNIT_HITPOINTS{"HITPOINTS", SQL_INT, true};
  constexpr Column           COLUMN_DATA_UNIT_CAPTURESPEED{"CAPTURESPEED", SQL_INT, true};
  constexpr Column           COLUMN_DATA_UNIT_IGNORESVISIONOCCLUSION{"IGNORESVISIONOCCLUSION", SQL_BOOL, true};
  constexpr Column           COLUMN_DATA_UNIT_STEALTHTYPE{"STEALTHTYPE", SQL_SMALLSTRING, true};
  constexpr Column           COLUMN_DATA_UNIT_STATIONARYFIRE{"STATIONARYFIRE", SQL_BOOL, true};
  constexpr std::string_view TABLE_DATA_UNIT_WEAPON = "UNIT_WEAPON_REFERENCE";
  constexpr Column           COLUMN_DATA_UNIT_WEAPON_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_DATA_UNIT_WEAPON_MOD_ID{"MOD_ID", SQL_INT};
  constexpr Column           COLUMN_DATA_UNIT_WEAPON_UNITNAME{"UNITTYPE_NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_UNIT_WEAPON_NAME{"WEAPONTYPE_NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_UNIT_WEAPON_ORDER{"WEAPONORDER", SQL_INT};
  constexpr std::string_view TABLE_DATA_UNIT_CLASSIFICATION = "UNIT_CLASSIFICATION_REFERENCE";
  constexpr Column           COLUMN_DATA_UNIT_CLASSIFICATION_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_DATA_UNIT_CLASSIFICATION_MOD_ID{"MOD_ID", SQL_INT};
  constexpr Column           COLUMN_DATA_UNIT_CLASSIFICATION_UNITNAME{"UNITTYPE_NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_UNIT_CLASSIFICATION_NAME{"CLASSIFICATION", SQL_SMALLSTRING};
  constexpr std::string_view TABLE_DATA_UNIT_TRANSPORT = "UNIT_TRANSPORTLIST_REFERENCE";
  constexpr Column           COLUMN_DATA_UNIT_TRANSPORT_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_DATA_UNIT_TRANSPORT_MOD_ID{"MOD_ID", SQL_INT};
  constexpr Column           COLUMN_DATA_UNIT_TRANSPORT_UNITNAME{"UNITTYPE_NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_UNIT_TRANSPORT_NAME{"TRANSPORTED_NAME", SQL_SMALLSTRING};

  constexpr std::string_view TABLE_DATA_WEAPON = "WEAPON_TYPE";
  constexpr Column           COLUMN_DATA_WEAPON_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_DATA_WEAPON_MOD_ID{"MOD_ID", SQL_INT};
  constexpr Column           COLUMN_DATA_WEAPON_NAME{"NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_WEAPON_AMMOCONSUMED{"AMMOCONSUMED", SQL_INT};
  constexpr Column           COLUMN_DATA_WEAPON_MAXRANGE{"MAXRANGE", SQL_INT};
  constexpr Column           COLUMN_DATA_WEAPON_MINRANGE{"MINRANGE", SQL_INT, true};
  constexpr Column           COLUMN_DATA_WEAPON_SELFTARGET{"SELFTARGET", SQL_BOOL, true};
  constexpr Column           COLUMN_DATA_WEAPON_AFFECTEDBYLUCK{"AFFECTEDBYLUCK", SQL_BOOL, true};
  constexpr Column           COLUMN_DATA_WEAPON_NONLETHAL{"NONLETHAL", SQL_BOOL, true};
  constexpr Column           COLUMN_DATA_WEAPON_AREAOFEFFECT{"AREAOFEFFECT", SQL_INT, true};
  constexpr Column           COLUMN_DATA_WEAPON_FLATDAMAGE{"FLATDAMAGE", SQL_INT, true};
  constexpr std::string_view TABLE_DATA_WEAPON_BASEDAMAGE = "WEAPON_BASEDAMAGE_REFERENCE";
  constexpr Column           COLUMN_DATA_WEAPON_BASEDAMAGE_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_DATA_WEAPON_BASEDAMAGE_MOD_ID{"MOD_ID", SQL_INT};
  constexpr Column           COLUMN_DATA_WEAPON_BASEDAMAGE_NAME{"WEAPONTYPE_NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_WEAPON_BASEDAMAGE_UNITNAME{"UNITTYPE_NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_WEAPON_BASEDAMAGE_DAMAGE{"DAMAGE", SQL_INT};
  constexpr std::string_view TABLE_DATA_WEAPON_STEALTHTARGET = "WEAPON_STEALTHTARGET_REFERENCE";
  constexpr Column           COLUMN_DATA_WEAPON_STEALTHTARGET_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_DATA_WEAPON_STEALTHTARGET_MOD_ID{"MOD_ID", SQL_INT};
  constexpr Column           COLUMN_DATA_WEAPON_STEALTHTARGET_WEAPON{"WEAPONTYPE_NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_WEAPON_STEALTHTARGET_STEALTHTYPE{"STEALTHTYPE", SQL_SMALLSTRING};
  
  constexpr std::string_view TABLE_DATA_TERRAIN = "TERRAIN_TYPE";
  constexpr Column           COLUMN_DATA_TERRAIN_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_DATA_TERRAIN_MOD_ID{"MOD_ID", SQL_INT};
  constexpr Column           COLUMN_DATA_TERRAIN_NAME{"NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_TERRAIN_STARS{"STARS", SQL_INT};
  constexpr Column           COLUMN_DATA_TERRAIN_MAXCAPTUREPOINTS{"MAXCAPTUREPOINTS", SQL_INT, true};
  constexpr Column           COLUMN_DATA_TERRAIN_SAMEAS{"SAMEAS", SQL_SMALLSTRING, true};
  constexpr Column           COLUMN_DATA_TERRAIN_INCOME{"INCOME", SQL_INT, true};
  constexpr Column           COLUMN_DATA_TERRAIN_REPAIR{"REPAIR", SQL_INT, true};
  constexpr Column           COLUMN_DATA_TERRAIN_OCCLUDESVISION{"OCCLUDESVISION", SQL_BOOL, true};
  constexpr Column           COLUMN_DATA_TERRAIN_HITPOINTS{"HITPOINTS", SQL_INT, true};
  constexpr Column           COLUMN_DATA_TERRAIN_DESTROYED{"DESTROYED", SQL_SMALLSTRING, true};
  constexpr Column           COLUMN_DATA_TERRAIN_DAMAGEDLIKE{"DAMAGEDLIKE", SQL_SMALLSTRING, true};
  constexpr Column           COLUMN_DATA_TERRAIN_ACTIVATIONMAX{"ACTIVATIONMAX", SQL_INT, true};
  constexpr Column           COLUMN_DATA_TERRAIN_ACTIVATIONCHANGE{"ACTIVATIONCHANGE", SQL_SMALLSTRING, true};
  constexpr Column           COLUMN_DATA_TERRAIN_LOSEIFCAPTURED{"LOSEIFCAPTURED", SQL_BOOL, true};
  constexpr Column           COLUMN_DATA_TERRAIN_LOSEIFALLCAPTURED{"LOSEIFALLCAPTURED", SQL_BOOL, true};
  constexpr Column           COLUMN_DATA_TERRAIN_DESTROYEDORIENTATION{"DESTROYEDORIENTATION", SQL_INT, true};
  constexpr std::string_view TABLE_DATA_TERRAIN_BUILDREPAIR = "TERRAIN_BUILDREPAIR_REFERENCE";
  constexpr Column           COLUMN_DATA_TERRAIN_BUILDREPAIR_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_DATA_TERRAIN_BUILDREPAIR_MOD_ID{"MOD_ID", SQL_INT};
  constexpr Column           COLUMN_DATA_TERRAIN_BUILDREPAIR_TERRAIN_NAME{"TERRAINTYPE_NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_TERRAIN_BUILDREPAIR_UNIT_NAME{"UNITTYPE_NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_TERRAIN_BUILDREPAIR_UNIT_ORDER{"UNITORDER", SQL_INT, true};
  constexpr Column           COLUMN_DATA_TERRAIN_BUILDREPAIR_TYPE{"BUILDREPAIR", SQL_INT};
  constexpr std::string_view TABLE_DATA_TERRAIN_ACTIVATIONLIST = "TERRAIN_ACTIVATIONLIST_REFERENCE";
  constexpr Column           COLUMN_DATA_TERRAIN_ACTIVATIONLIST_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_DATA_TERRAIN_ACTIVATIONLIST_MOD_ID{"MOD_ID", SQL_INT};
  constexpr Column           COLUMN_DATA_TERRAIN_ACTIVATIONLIST_TERRAIN_NAME{"TERRAINTYPE_NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_TERRAIN_ACTIVATIONLIST_UNIT_NAME{"UNITTYPE_NAME", SQL_SMALLSTRING};
  constexpr std::string_view TABLE_DATA_TERRAIN_ACTIVATIONEFFECT = "TERRAIN_ACTIVATIONEFFECT_REFERENCE";
  constexpr Column           COLUMN_DATA_TERRAIN_ACTIVATIONEFFECT_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_DATA_TERRAIN_ACTIVATIONEFFECT_MOD_ID{"MOD_ID", SQL_INT};
  constexpr Column           COLUMN_DATA_TERRAIN_ACTIVATIONEFFECT_TERRAIN_NAME{"TERRAINTYPE_NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_TERRAIN_ACTIVATIONEFFECT_EFFECT_TYPE{"EFFECT_TYPE", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_TERRAIN_ACTIVATIONEFFECT_EFFECT_NAME{"EFFECT_NAME", SQL_SMALLSTRING};
  
  constexpr std::string_view TABLE_DATA_COMMANDER = "COMMANDER_TYPE";
  constexpr Column           COLUMN_DATA_COMMANDER_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_DATA_COMMANDER_MOD_ID{"MOD_ID", SQL_INT};
  constexpr Column           COLUMN_DATA_COMMANDER_NAME{"NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_COMMANDER_COPCOST{"COPCOST", SQL_INT, true};
  constexpr Column           COLUMN_DATA_COMMANDER_SCOPCOST{"SCOPCOST", SQL_INT, true};
  constexpr Column           COLUMN_DATA_COMMANDER_COMETERMULTIPLIER{"COMETERMULTIPLIER", SQL_INT, true};
  constexpr Column           COLUMN_DATA_COMMANDER_PLAYABLE{"PLAYABLE", SQL_BOOL, true};
  constexpr std::string_view TABLE_DATA_COMMANDER_EFFECT = "COMMANDER_EFFECT_REFERENCE";
  constexpr Column           COLUMN_DATA_COMMANDER_EFFECT_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_DATA_COMMANDER_EFFECT_MOD_ID{"MOD_ID", SQL_INT};
  constexpr Column           COLUMN_DATA_COMMANDER_EFFECT_COMMANDER_NAME{"COMMANDER_NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_COMMANDER_EFFECT_NAME{"EFFECT_NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_COMMANDER_EFFECT_TYPE{"EFFECT_TYPE", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_COMMANDER_EFFECT_CATEGORY{"EFFECT_CATEGORY", SQL_INT};

  constexpr std::string_view TABLE_DATA_MOVEMENT = "MOVEMENT_TYPE";
  constexpr Column           COLUMN_DATA_MOVEMENT_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_DATA_MOVEMENT_MOD_ID{"MOD_ID", SQL_INT};
  constexpr Column           COLUMN_DATA_MOVEMENT_NAME{"NAME", SQL_SMALLSTRING};
  constexpr std::string_view TABLE_DATA_MOVEMENT_COST = "MOVEMENT_COST_REFERENCE";
  constexpr Column           COLUMN_DATA_MOVEMENT_COST_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_DATA_MOVEMENT_COST_MOD_ID{"MOD_ID", SQL_INT};
  constexpr Column           COLUMN_DATA_MOVEMENT_COST_NAME{"MOVEMENT_NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_MOVEMENT_COST_TERRAIN{"TERRAINTYPE_NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_MOVEMENT_COST_COST{"COST", SQL_INT};
  constexpr Column           COLUMN_DATA_MOVEMENT_COST_VARIANT{"VARIANT", SQL_SMALLSTRING, true};
  constexpr std::string_view TABLE_DATA_MOVEMENT_RULE_REF = "MOVEMENT_RULE_REFERENCE";
  constexpr Column           COLUMN_DATA_MOVEMENT_RULE_REF_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_DATA_MOVEMENT_RULE_REF_MOD_ID{"MOD_ID", SQL_INT};
  constexpr Column           COLUMN_DATA_MOVEMENT_RULE_REF_NAME{"MOVEMENT_NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_MOVEMENT_RULE_REF_RULE{"RULE_NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_MOVEMENT_RULE_REF_ORDER{"ORDER", SQL_INT};
  
  constexpr std::string_view TABLE_DATA_MOVEMENT_RULE = "MOVEMENT_RULE";
  constexpr Column           COLUMN_DATA_MOVEMENT_RULE_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_DATA_MOVEMENT_RULE_MOD_ID{"MOD_ID", SQL_INT};
  constexpr Column           COLUMN_DATA_MOVEMENT_RULE_NAME{"NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_MOVEMENT_RULE_TYPE{"TYPE", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_MOVEMENT_RULE_MAXREPEAT{"MAXREPEAT", SQL_INT};
  constexpr Column           COLUMN_DATA_MOVEMENT_RULE_CONFIRMTYPE{"CONFIRMTYPE", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_MOVEMENT_RULE_STOPIFUSED{"STOPIFUSED", SQL_BOOL};
  
  constexpr std::string_view TABLE_DATA_PLAYER = "PLAYER_TYPE";
  constexpr Column           COLUMN_DATA_PLAYER_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_DATA_PLAYER_MOD_ID{"MOD_ID", SQL_INT};
  constexpr Column           COLUMN_DATA_PLAYER_NAME{"NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_PLAYER_COMMANDERMOD{"COMMANDERTYPEMOD", SQL_SMALLSTRING, true};
  constexpr Column           COLUMN_DATA_PLAYER_TEAM{"TEAMNAME", SQL_SMALLSTRING, true};
  constexpr std::string_view TABLE_DATA_PLAYER_PERMITTEDPLAYERSLOT = "PLAYER_PERMITTEDPLAYERSLOT_REFERENCE";
  constexpr Column           COLUMN_DATA_PLAYER_PERMITTEDPLAYERSLOT_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_DATA_PLAYER_PERMITTEDPLAYERSLOT_MOD_ID{"MOD_ID", SQL_INT};
  constexpr Column           COLUMN_DATA_PLAYER_PERMITTEDPLAYERSLOT_NAME{"PLAYERTYPE_NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_PLAYER_PERMITTEDPLAYERSLOT_SLOT{"PERMITTEDPLAYERSLOT", SQL_SMALLSTRING};
  constexpr std::string_view TABLE_DATA_PLAYER_PERMITTEDCOMMANDERTYPE = "PLAYER_PERMITTEDCOMMANDERTYPE_REFERENCE";
  constexpr Column           COLUMN_DATA_PLAYER_PERMITTEDCOMMANDERTYPE_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_DATA_PLAYER_PERMITTEDCOMMANDERTYPE_MOD_ID{"MOD_ID", SQL_INT};
  constexpr Column           COLUMN_DATA_PLAYER_PERMITTEDCOMMANDERTYPE_NAME{"PLAYERTYPE_NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_PLAYER_PERMITTEDCOMMANDERTYPE_COMMANDER{"PERMITTEDCOMMANDERTYPE", SQL_SMALLSTRING};
  
  constexpr std::string_view TABLE_DATA_EFFECT_TARGET = "EFFECT_TARGET_REFERENCE";
  constexpr Column           COLUMN_DATA_EFFECT_TARGET_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_DATA_EFFECT_TARGET_MOD_ID{"MOD_ID", SQL_INT};
  constexpr Column           COLUMN_DATA_EFFECT_TARGET_EFFECT_NAME{"EFFECT_NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_EFFECT_TARGET_TYPE{"EFFECT_TYPE", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_EFFECT_TARGET_TARGET{"TARGET", SQL_SMALLSTRING};
  constexpr std::string_view TABLE_DATA_EFFECT_AFFECT = "EFFECT_AFFECT_REFERENCE";
  constexpr Column           COLUMN_DATA_EFFECT_AFFECT_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_DATA_EFFECT_AFFECT_MOD_ID{"MOD_ID", SQL_INT};
  constexpr Column           COLUMN_DATA_EFFECT_AFFECT_EFFECT_NAME{"EFFECT_NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_EFFECT_AFFECT_TYPE{"EFFECT_TYPE", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_EFFECT_AFFECT_AFFECTS{"AFFECTS", SQL_SMALLSTRING};
  constexpr std::string_view TABLE_DATA_EFFECT_CLASSIFICATION = "EFFECT_CLASSIFICATION_REFERENCE";
  constexpr Column           COLUMN_DATA_EFFECT_CLASSIFICATION_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_DATA_EFFECT_CLASSIFICATION_MOD_ID{"MOD_ID", SQL_INT};
  constexpr Column           COLUMN_DATA_EFFECT_CLASSIFICATION_EFFECT_NAME{"EFFECT_NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_EFFECT_CLASSIFICATION_TYPE{"EFFECT_TYPE", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_EFFECT_CLASSIFICATION_CLASSIFICATION{"CLASSIFICATION", SQL_SMALLSTRING};
  constexpr std::string_view TABLE_DATA_EFFECT_TERRAIN = "EFFECT_TERRAIN_REFERENCE";
  constexpr Column           COLUMN_DATA_EFFECT_TERRAIN_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_DATA_EFFECT_TERRAIN_MOD_ID{"MOD_ID", SQL_INT};
  constexpr Column           COLUMN_DATA_EFFECT_TERRAIN_EFFECT_NAME{"EFFECT_NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_EFFECT_TERRAIN_TYPE{"EFFECT_TYPE", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_EFFECT_TERRAIN_TERRAIN{"TERRAINTYPE_NAME", SQL_SMALLSTRING};
  constexpr std::string_view TABLE_DATA_EFFECT_UNITTYPEREQUIRED = "EFFECT_UNITTYPEREQUIRED_REFERENCE";
  constexpr Column           COLUMN_DATA_EFFECT_UNITTYPEREQUIRED_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_DATA_EFFECT_UNITTYPEREQUIRED_MOD_ID{"MOD_ID", SQL_INT};
  constexpr Column           COLUMN_DATA_EFFECT_UNITTYPEREQUIRED_EFFECT_NAME{"EFFECT_NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_EFFECT_UNITTYPEREQUIRED_TYPE{"EFFECT_TYPE", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_EFFECT_UNITTYPEREQUIRED_UNIT{"UNITTYPE_NAME", SQL_SMALLSTRING};
  
  constexpr std::string_view TABLE_DATA_PASSIVE_UNIT_EFFECT = "PASSIVE_UNIT_EFFECT";
  constexpr Column           COLUMN_DATA_PASSIVE_UNIT_EFFECT_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_DATA_PASSIVE_UNIT_EFFECT_MOD_ID{"MOD_ID", SQL_INT};
  constexpr Column           COLUMN_DATA_PASSIVE_UNIT_EFFECT_NAME{"NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_PASSIVE_UNIT_EFFECT_FIREPOWER{"FIREPOWERMOD", SQL_INT, true};
  constexpr Column           COLUMN_DATA_PASSIVE_UNIT_EFFECT_DEFENSE{"DEFENSEMOD", SQL_INT, true};
  constexpr Column           COLUMN_DATA_PASSIVE_UNIT_EFFECT_INDIRECTDEFENSE{"INDIRECTDEFENSEMOD", SQL_INT, true};
  constexpr Column           COLUMN_DATA_PASSIVE_UNIT_EFFECT_MINRANGE{"MINRANGEMOD", SQL_INT, true};
  constexpr Column           COLUMN_DATA_PASSIVE_UNIT_EFFECT_MAXRANGE{"MAXRANGEMOD", SQL_INT, true};
  constexpr Column           COLUMN_DATA_PASSIVE_UNIT_EFFECT_FUELUSE{"FUELUSEMOD", SQL_INT, true};
  constexpr Column           COLUMN_DATA_PASSIVE_UNIT_EFFECT_AMMOUSE{"AMMOUSEMOD", SQL_INT, true};
  constexpr Column           COLUMN_DATA_PASSIVE_UNIT_EFFECT_GOODLUCK{"GOODLUCKMOD", SQL_INT, true};
  constexpr Column           COLUMN_DATA_PASSIVE_UNIT_EFFECT_BADLUCK{"BADLUCKMOD", SQL_INT, true};
  constexpr Column           COLUMN_DATA_PASSIVE_UNIT_EFFECT_MOVEMENT{"MOVEMENTMOD", SQL_INT, true};
  constexpr Column           COLUMN_DATA_PASSIVE_UNIT_EFFECT_VISION{"VISIONMOD", SQL_INT, true};
  constexpr Column           COLUMN_DATA_PASSIVE_UNIT_EFFECT_TERRAINSTARS{"TERRAINSTARSMOD", SQL_INT, true};
  constexpr Column           COLUMN_DATA_PASSIVE_UNIT_EFFECT_TERRAINSTARSFLAT{"TERRAINSTARSFLATMOD", SQL_INT, true};
  constexpr Column           COLUMN_DATA_PASSIVE_UNIT_EFFECT_TERRAINDEFENSE{"TERRAINSTARSDEFENSE", SQL_INT, true};
  constexpr Column           COLUMN_DATA_PASSIVE_UNIT_EFFECT_TERRAINFIREPOWER{"TERRAINSTARSFIREPOWER", SQL_INT, true};
  constexpr Column           COLUMN_DATA_PASSIVE_UNIT_EFFECT_COUNTERFIRE{"COUNTERFIREMOD", SQL_INT, true};
  constexpr Column           COLUMN_DATA_PASSIVE_UNIT_EFFECT_COUNTERFIRST{"COUNTERFIRST", SQL_BOOL, true};
  constexpr Column           COLUMN_DATA_PASSIVE_UNIT_EFFECT_CAPTURERATE{"CAPTURERATEMOD", SQL_INT, true};
  constexpr Column           COLUMN_DATA_PASSIVE_UNIT_EFFECT_UNITCOST{"UNITCOSTMOD", SQL_INT, true};
  constexpr Column           COLUMN_DATA_PASSIVE_UNIT_EFFECT_FIREPOWERFROMFUNDS{"FIREPOWERFROMFUNDS", SQL_INT, true};
  constexpr Column           COLUMN_DATA_PASSIVE_UNIT_EFFECT_DEFENSEFROMFUNDS{"DEFENSEFROMFUNDS", SQL_INT, true};
  constexpr Column           COLUMN_DATA_PASSIVE_UNIT_EFFECT_FUNDSFROMDAMAGE{"FUNDSFROMDAMAGE", SQL_INT, true};
  constexpr Column           COLUMN_DATA_PASSIVE_UNIT_EFFECT_COMETERCHARGEFROMDEALTDAMAGE{"COMETERCHARGEFROMDEALTDAMAGE", SQL_INT, true};
  constexpr Column           COLUMN_DATA_PASSIVE_UNIT_EFFECT_COMETERCHARGEFROMRECEIVEDDAMAGE{"COMETERCHARGEFROMRECEIVEDDAMAGE", SQL_INT, true};
  constexpr Column           COLUMN_DATA_PASSIVE_UNIT_EFFECT_TERRAINSTARSFLATDEFENSE{"TERRAINSTARSFLATDEFENSE", SQL_INT, true};
  constexpr Column           COLUMN_DATA_PASSIVE_UNIT_EFFECT_TERRAINSTARSFLATFIREPOWER{"TERRAINSTARSFLATFIREPOWER", SQL_INT, true};
  constexpr std::string_view TABLE_DATA_PUE_FIREPOWERFROMTERRAIN = "PUE_FIREPOWERFROMTERRAIN_REFERENCE";
  constexpr Column           COLUMN_DATA_PUE_FIREPOWERFROMTERRAIN_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_DATA_PUE_FIREPOWERFROMTERRAIN_MOD_ID{"MOD_ID", SQL_INT};
  constexpr Column           COLUMN_DATA_PUE_FIREPOWERFROMTERRAIN_EFFECT_NAME{"EFFECT_NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_PUE_FIREPOWERFROMTERRAIN_TERRAIN{"TERRAINTYPE_NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_PUE_FIREPOWERFROMTERRAIN_FIREPOWER{"FIREPOWERMOD", SQL_INT};
  constexpr std::string_view TABLE_DATA_PUE_DEFENSEFROMTERRAIN = "PUE_DEFENSEFROMTERRAIN_REFERENCE";
  constexpr Column           COLUMN_DATA_PUE_DEFENSEFROMTERRAIN_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_DATA_PUE_DEFENSEFROMTERRAIN_MOD_ID{"MOD_ID", SQL_INT};
  constexpr Column           COLUMN_DATA_PUE_DEFENSEFROMTERRAIN_EFFECT_NAME{"EFFECT_NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_PUE_DEFENSEFROMTERRAIN_TERRAIN{"TERRAINTYPE_NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_PUE_DEFENSEFROMTERRAIN_DEFENSE{"DEFENSEMOD", SQL_INT};
  constexpr std::string_view TABLE_DATA_PUE_VISIONVARIANT = "PUE_VISIONVARIANT_REFERENCE";
  constexpr Column           COLUMN_DATA_PUE_VISIONVARIANT_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_DATA_PUE_VISIONVARIANT_MOD_ID{"MOD_ID", SQL_INT};
  constexpr Column           COLUMN_DATA_PUE_VISIONVARIANT_EFFECT_NAME{"EFFECT_NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_PUE_VISIONVARIANT_VARIANT{"VARIANT", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_PUE_VISIONVARIANT_VISION{"VISIONMOD", SQL_INT};
  constexpr std::string_view TABLE_DATA_PUE_FIREPOWERVARIANT = "PUE_FIREPOWERVARIANT_REFERENCE";
  constexpr Column           COLUMN_DATA_PUE_FIREPOWERVARIANT_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_DATA_PUE_FIREPOWERVARIANT_MOD_ID{"MOD_ID", SQL_INT};
  constexpr Column           COLUMN_DATA_PUE_FIREPOWERVARIANT_EFFECT_NAME{"EFFECT_NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_PUE_FIREPOWERVARIANT_VARIANT{"VARIANT", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_PUE_FIREPOWERVARIANT_FIREPOWER{"FIREPOWERMOD", SQL_INT};
  constexpr std::string_view TABLE_DATA_PUE_DEFENSEVARIANT = "PUE_DEFENSEVARIANT_REFERENCE";
  constexpr Column           COLUMN_DATA_PUE_DEFENSEVARIANT_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_DATA_PUE_DEFENSEVARIANT_MOD_ID{"MOD_ID", SQL_INT};
  constexpr Column           COLUMN_DATA_PUE_DEFENSEVARIANT_EFFECT_NAME{"EFFECT_NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_PUE_DEFENSEVARIANT_VARIANT{"VARIANT", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_PUE_DEFENSEVARIANT_DEFENSE{"DEFENSEMOD", SQL_INT};
  constexpr std::string_view TABLE_DATA_PUE_INTEL = "PUE_INTEL_REFERENCE";
  constexpr Column           COLUMN_DATA_PUE_INTEL_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_DATA_PUE_INTEL_MOD_ID{"MOD_ID", SQL_INT};
  constexpr Column           COLUMN_DATA_PUE_INTEL_EFFECT_NAME{"EFFECT_NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_PUE_INTEL_TYPE{"INTEL_TYPE", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_PUE_INTEL_TARGET{"TARGET", SQL_SMALLSTRING};
  
  constexpr std::string_view TABLE_DATA_ACTIVE_UNIT_EFFECT = "ACTIVE_UNIT_EFFECT";
  constexpr Column           COLUMN_DATA_ACTIVE_UNIT_EFFECT_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_DATA_ACTIVE_UNIT_EFFECT_MOD_ID{"MOD_ID", SQL_INT};
  constexpr Column           COLUMN_DATA_ACTIVE_UNIT_EFFECT_NAME{"NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_ACTIVE_UNIT_EFFECT_HITPOINT{"HITPOINTMOD", SQL_INT, true};
  constexpr Column           COLUMN_DATA_ACTIVE_UNIT_EFFECT_ROUNDHITPOINT{"ROUNDHITPOINTS", SQL_INT, true};
  constexpr Column           COLUMN_DATA_ACTIVE_UNIT_EFFECT_SETFUEL{"SETFUEL", SQL_INT, true};
  constexpr Column           COLUMN_DATA_ACTIVE_UNIT_EFFECT_SETAMMO{"SETAMMO", SQL_INT, true};
  constexpr Column           COLUMN_DATA_ACTIVE_UNIT_EFFECT_ADDFUEL{"ADDFUEL", SQL_INT, true};
  constexpr Column           COLUMN_DATA_ACTIVE_UNIT_EFFECT_ADDAMMO{"ADDAMMO", SQL_INT, true};
  constexpr Column           COLUMN_DATA_ACTIVE_UNIT_EFFECT_MULTIPLYFUEL{"MULTIPLYFUEL", SQL_INT, true};
  constexpr Column           COLUMN_DATA_ACTIVE_UNIT_EFFECT_MULTIPLYAMMO{"MULTIPLYAMMO", SQL_INT, true};
  constexpr Column           COLUMN_DATA_ACTIVE_UNIT_EFFECT_MAKEACTIVE{"MAKEACTIVE", SQL_BOOL, true};
  constexpr Column           COLUMN_DATA_ACTIVE_UNIT_EFFECT_STUNDURATION{"STUNDURATION", SQL_INT, true};
  constexpr Column           COLUMN_DATA_ACTIVE_UNIT_EFFECT_COCHARGEFACTOR{"COCHARGEFACTOR", SQL_INT, true};
  
  constexpr std::string_view TABLE_DATA_PASSIVE_TERRAIN_EFFECT = "PASSIVE_TERRAIN_EFFECT";
  constexpr Column           COLUMN_DATA_PASSIVE_TERRAIN_EFFECT_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_DATA_PASSIVE_TERRAIN_EFFECT_MOD_ID{"MOD_ID", SQL_INT};
  constexpr Column           COLUMN_DATA_PASSIVE_TERRAIN_EFFECT_NAME{"NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_PASSIVE_TERRAIN_EFFECT_INCOME{"INCOMEMOD", SQL_INT, true};
  constexpr Column           COLUMN_DATA_PASSIVE_TERRAIN_EFFECT_INCOMEFLAT{"INCOMEFLATMOD", SQL_INT, true};
  constexpr Column           COLUMN_DATA_PASSIVE_TERRAIN_EFFECT_REPAIR{"REPAIRMOD", SQL_INT, true};
  constexpr Column           COLUMN_DATA_PASSIVE_TERRAIN_EFFECT_OCCLUDESVISION{"OCCLUDESVISIONMOD", SQL_BOOL, true};
  constexpr Column           COLUMN_DATA_PASSIVE_TERRAIN_EFFECT_VISION{"VISIONMODBOOST", SQL_INT, true};
  constexpr Column           COLUMN_DATA_PASSIVE_TERRAIN_EFFECT_BUILDCOST{"BUILDCOSTMOD", SQL_INT, true};
  constexpr std::string_view TABLE_DATA_PTE_BUILDLISTMOD = "PTE_BUILDLISTMOD_REFERENCE";
  constexpr Column           COLUMN_DATA_PTE_BUILDLISTMOD_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_DATA_PTE_BUILDLISTMOD_MOD_ID{"MOD_ID", SQL_INT};
  constexpr Column           COLUMN_DATA_PTE_BUILDLISTMOD_EFFECT_NAME{"EFFECT_NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_PTE_BUILDLISTMOD_UNIT{"UNITTYPE_NAME", SQL_SMALLSTRING};
  
  constexpr std::string_view TABLE_DATA_ACTIVE_TERRAIN_EFFECT = "ACTIVE_TERRAIN_EFFECT";
  constexpr Column           COLUMN_DATA_ACTIVE_TERRAIN_EFFECT_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_DATA_ACTIVE_TERRAIN_EFFECT_MOD_ID{"MOD_ID", SQL_INT};
  constexpr Column           COLUMN_DATA_ACTIVE_TERRAIN_EFFECT_NAME{"NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_ACTIVE_TERRAIN_EFFECT_UNITSUMMONEDNAME{"UNITSUMMONEDNAME", SQL_SMALLSTRING, true};
  constexpr Column           COLUMN_DATA_ACTIVE_TERRAIN_EFFECT_UNITSUMMONEDDAMAGE{"UNITSUMMONEDINITIALDAMAGE", SQL_INT, true};
  constexpr Column           COLUMN_DATA_ACTIVE_TERRAIN_EFFECT_UNITSUMMONEDACTIVE{"UNITSUMMONEDACTIVE", SQL_BOOL, true};
  
  constexpr std::string_view TABLE_DATA_PASSIVE_GLOBAL_EFFECT = "PASSIVE_GLOBAL_EFFECT";
  constexpr Column           COLUMN_DATA_PASSIVE_GLOBAL_EFFECT_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_DATA_PASSIVE_GLOBAL_EFFECT_MOD_ID{"MOD_ID", SQL_INT};
  constexpr Column           COLUMN_DATA_PASSIVE_GLOBAL_EFFECT_NAME{"NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_PASSIVE_GLOBAL_EFFECT_VARIANT{"VARIANTMOD", SQL_SMALLSTRING, true};
  constexpr Column           COLUMN_DATA_PASSIVE_GLOBAL_EFFECT_MOVEMENTVARIANTREPLACE{"MOVEMENTCLASSVARIANTREPLACE", SQL_SMALLSTRING, true};
  constexpr Column           COLUMN_DATA_PASSIVE_GLOBAL_EFFECT_MOVEMENTVARIANTOVERRIDE{"MOVEMENTCLASSVARIANTOVERRIDE", SQL_SMALLSTRING, true};
  constexpr Column           COLUMN_DATA_PASSIVE_GLOBAL_EFFECT_MINIMUMVISIONMOD{"MINIMUMVISIONMOD", SQL_INT, true};
  constexpr std::string_view TABLE_DATA_PGE_VARIANTHINTMOD = "PGE_VARIANTHINTMOD_REFERENCE";
  constexpr Column           COLUMN_DATA_PGE_VARIANTHINTMOD_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_DATA_PGE_VARIANTHINTMOD_MOD_ID{"MOD_ID", SQL_INT};
  constexpr Column           COLUMN_DATA_PGE_VARIANTHINTMOD_EFFECT_NAME{"EFFECT_NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_PGE_VARIANTHINTMOD_EFFECT_VARIANT{"VARIANT", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_PGE_VARIANTHINTMOD_HINT{"HINTMOD", SQL_INT};
  
  constexpr std::string_view TABLE_DATA_ACTIVE_GLOBAL_EFFECT = "ACTIVE_GLOBAL_EFFECT";
  constexpr Column           COLUMN_DATA_ACTIVE_GLOBAL_EFFECT_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_DATA_ACTIVE_GLOBAL_EFFECT_MOD_ID{"MOD_ID", SQL_INT};
  constexpr Column           COLUMN_DATA_ACTIVE_GLOBAL_EFFECT_NAME{"NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_ACTIVE_GLOBAL_EFFECT_FUND{"FUNDMOD", SQL_INT, true};
  constexpr Column           COLUMN_DATA_ACTIVE_GLOBAL_EFFECT_FUNDFLAT{"FUNDFLATMOD", SQL_INT, true};
  constexpr Column           COLUMN_DATA_ACTIVE_GLOBAL_EFFECT_POWERBAR{"POWERBARMOD", SQL_INT, true};
  constexpr Column           COLUMN_DATA_ACTIVE_GLOBAL_EFFECT_POWERBARPERFUNDS{"POWERBARPERFUNDS", SQL_INT, true};
  constexpr Column           COLUMN_DATA_ACTIVE_GLOBAL_EFFECT_MISSILECOUNT{"MISSILECOUNT", SQL_INT, true};
  constexpr Column           COLUMN_DATA_ACTIVE_GLOBAL_EFFECT_MISSILEDAMAGE{"MISSILEDAMAGE", SQL_INT, true};
  constexpr Column           COLUMN_DATA_ACTIVE_GLOBAL_EFFECT_MISSILEAREAOFEFFECT{"MISSILEAREAOFEFFECT", SQL_INT, true};
  constexpr Column           COLUMN_DATA_ACTIVE_GLOBAL_EFFECT_MISSILESTUNDURATION{"MISSILESTUNDURATION", SQL_INT, true};
  constexpr Column           COLUMN_DATA_ACTIVE_GLOBAL_EFFECT_COCHARGEFACTOR{"COCHARGEFACTOR", SQL_INT, true};
  constexpr std::string_view TABLE_DATA_AGE_MISSILETARGETMETHOD = "AGE_MISSILETARGETMETHOD_REFERENCE";
  constexpr Column           COLUMN_DATA_AGE_MISSILETARGETMETHOD_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_DATA_AGE_MISSILETARGETMETHOD_MOD_ID{"MOD_ID", SQL_INT};
  constexpr Column           COLUMN_DATA_AGE_MISSILETARGETMETHOD_EFFECT_NAME{"EFFECT_NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_AGE_MISSILETARGETMETHOD_EFFECT_TARGET_METHOD{"TARGETMETHOD", SQL_SMALLSTRING};
  
  constexpr std::string_view TABLE_DATA_DEFAULT_GAME_SETTINGS = "DEFAULT_GAME_SETTINGS";
  constexpr Column           COLUMN_DATA_SETTINGS_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_DATA_SETTINGS_MOD_ID{"MOD_ID", SQL_INT};
  constexpr Column           COLUMN_DATA_SETTINGS_NAME{"NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_SETTINGS_FOG{"FOGOFWAR", SQL_BOOL, true};
  constexpr Column           COLUMN_DATA_SETTINGS_POWERS{"COPOWERS", SQL_BOOL, true};
  constexpr Column           COLUMN_DATA_SETTINGS_TEAMS{"TEAMS", SQL_BOOL, true};
  constexpr Column           COLUMN_DATA_SETTINGS_STARTINGFUNDS{"STARTINGFUNDS", SQL_INT, true};
  constexpr Column           COLUMN_DATA_SETTINGS_INCOMEMULTIPLIER{"INCOMEMULTIPLIER", SQL_INT, true};
  constexpr Column           COLUMN_DATA_SETTINGS_UNITLIMIT{"UNITLIMIT", SQL_INT, true};
  constexpr Column           COLUMN_DATA_SETTINGS_CAPTURELIMIT{"CAPTURELIMIT", SQL_INT, true};
  constexpr Column           COLUMN_DATA_SETTINGS_DAYLIMIT{"DAYLIMIT", SQL_INT, true};
  constexpr Column           COLUMN_DATA_SETTINGS_COMETERSIZE{"COMETERSIZE", SQL_INT, true};
  constexpr Column           COLUMN_DATA_SETTINGS_COMETERMULTIPLIER{"COMETERMULTIPLIER", SQL_INT, true};
  constexpr std::string_view TABLE_DATA_DEFAULTSETTINGS_VARIANT = "DEFAULTSETTINGS_VARIANT_REFERENCE";
  constexpr Column           COLUMN_DATA_SETTINGS_VARIANT_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_DATA_SETTINGS_VARIANT_MOD_ID{"MOD_ID", SQL_INT};
  constexpr Column           COLUMN_DATA_SETTINGS_VARIANT_SETTING{"SETTING_NAME", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_SETTINGS_VARIANT_VARIANT{"VARIANT", SQL_SMALLSTRING};
  constexpr Column           COLUMN_DATA_SETTINGS_VARIANT_VALUE{"VALUE", SQL_INT};
  
  constexpr std::string_view TABLE_DATA_CONFIG = "CONFIG";
  constexpr Column           COLUMN_DATA_CONFIG_ID{"ID", SQL_INT, false, true};
  constexpr Column           COLUMN_DATA_CONFIG_MOD_ID{"MOD_ID", SQL_INT};
  constexpr Column           COLUMN_DATA_CONFIG_MINTERRAINSTARS{"MINTERRAINSTARS", SQL_INT, true};
  constexpr Column           COLUMN_DATA_CONFIG_UNLIMITEDUNLOAD{"UNLIMITEDUNLOAD", SQL_BOOL, true};
  constexpr Column           COLUMN_DATA_CONFIG_TERRAINDEFENSESCALES{"TERRAINDEFENSESCALESWITHHITPOINTS", SQL_BOOL, true};
  constexpr Column           COLUMN_DATA_CONFIG_TERRAINFIREPOWERSCALES{"TERRAINFIREPOWERSCALESWITHHITPOINTS", SQL_BOOL, true};

  DBErrorCode buildDatabase();
}