#pragma once
#include <dbs/DBType.h>

#include <experimental/array>

namespace db::v0_0_1 {
using std::experimental::make_array;
constexpr std::string_view CURRENT_VERSION = "0.0.1";

constexpr std::string_view DB_GENERAL = "GENERAL";
constexpr std::string_view DB_DATA = "DATA";
constexpr std::string_view DB_STATE = "STATE";
constexpr std::string_view DB_RESOURCE = "RESOURCE";

constexpr std::string_view TABLE_META = "META";
constexpr Column COLUMN_META_VERSION{"VERSION", SQL_SMALLSTRING};
constexpr Column COLUMN_META_PROTECTED{"PROTECTED", SQL_BOOL};
constexpr auto TABLE_META_COLUMNS = make_array(COLUMN_META_VERSION, COLUMN_META_PROTECTED);

constexpr std::string_view TABLE_IMAGE_RESOURCE = "IMAGE_RESOURCE";
constexpr Column COLUMN_IMAGERESOURCE_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_IMAGERESOURCE_PACK_ID{"PACK_ID", SQL_INT};
constexpr Column COLUMN_IMAGERESOURCE_KEY{"KEY", SQL_SMALLSTRING};
constexpr Column COLUMN_IMAGERESOURCE_TYPE{"TYPE", SQL_SMALLSTRING};
constexpr Column COLUMN_IMAGERESOURCE_ARMYCOLOR{"ARMYCOLOR", SQL_SMALLSTRING, true};
constexpr Column COLUMN_IMAGERESOURCE_ORIENTATION{"ORIENTATION", SQL_INT, true};
constexpr Column COLUMN_IMAGERESOURCE_VARIANT{"VARIANT", SQL_SMALLSTRING, true};
constexpr Column COLUMN_IMAGERESOURCE_ORDER{"ORDER", SQL_INT, true};
constexpr Column COLUMN_IMAGERESOURCE_SMALLIMAGE{"SMALLIMAGE", SQL_LARGESTRING, true};
constexpr Column COLUMN_IMAGERESOURCE_LARGEIMAGE{"LARGEIMAGE", SQL_LARGESTRING, true};
constexpr Column COLUMN_IMAGERESOURCE_SMALLIMAGEBLOB{"SMALLIMAGEBLOB", SQL_BLOB, true};
constexpr Column COLUMN_IMAGERESOURCE_LARGEIMAGEBLOB{"LARGEIMAGEBLOB", SQL_BLOB, true};
constexpr auto TABLE_IMAGE_RESOURCE_COLUMNS = make_array(
    COLUMN_IMAGERESOURCE_ID, COLUMN_IMAGERESOURCE_PACK_ID, COLUMN_IMAGERESOURCE_KEY, COLUMN_IMAGERESOURCE_TYPE, COLUMN_IMAGERESOURCE_ARMYCOLOR,
    COLUMN_IMAGERESOURCE_ORIENTATION, COLUMN_IMAGERESOURCE_VARIANT, COLUMN_IMAGERESOURCE_ORDER, COLUMN_IMAGERESOURCE_SMALLIMAGE,
    COLUMN_IMAGERESOURCE_LARGEIMAGE, COLUMN_IMAGERESOURCE_SMALLIMAGEBLOB, COLUMN_IMAGERESOURCE_LARGEIMAGEBLOB);
constexpr std::string_view TABLE_TEXT_RESOURCE = "TEXT_RESOURCE";
constexpr Column COLUMN_TEXTRESOURCE_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_TEXTRESOURCE_PACK_ID{"PACK_ID", SQL_INT};
constexpr Column COLUMN_TEXTRESOURCE_KEY{"KEY", SQL_SMALLSTRING};
constexpr Column COLUMN_TEXTRESOURCE_TYPE{"TYPE", SQL_SMALLSTRING};
constexpr Column COLUMN_TEXTRESOURCE_SHORTNAME{"SHORTNAME", SQL_SMALLSTRING};
constexpr Column COLUMN_TEXTRESOURCE_LONGNAME{"LONGNAME", SQL_SMALLSTRING};
constexpr Column COLUMN_TEXTRESOURCE_DESCRIPTION{"DESCRIPTION", SQL_LARGESTRING};
constexpr Column COLUMN_TEXTRESOURCE_LANGUAGE{"LANGUAGE", SQL_SMALLSTRING, true};
constexpr auto TABLE_TEXT_RESOURCE_COLUMNS =
    make_array(COLUMN_TEXTRESOURCE_ID, COLUMN_TEXTRESOURCE_PACK_ID, COLUMN_TEXTRESOURCE_KEY, COLUMN_TEXTRESOURCE_TYPE, COLUMN_TEXTRESOURCE_SHORTNAME,
               COLUMN_TEXTRESOURCE_LONGNAME, COLUMN_TEXTRESOURCE_DESCRIPTION, COLUMN_TEXTRESOURCE_LANGUAGE);
constexpr std::string_view TABLE_PACK = "PACK";
constexpr Column COLUMN_RESOURCEPACK_PACK_ID{"PACK_ID", SQL_INT, false, true};
constexpr Column COLUMN_RESOURCEPACK_NAME{"NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_RESOURCEPACK_VERSION{"VERSION", SQL_SMALLSTRING};
constexpr Column COLUMN_RESOURCEPACK_CREATED{"CREATED", SQL_DATETIME};
constexpr Column COLUMN_RESOURCEPACK_EXPIRED{"EXPIRED", SQL_DATETIME, true};
constexpr Column COLUMN_RESOURCEPACK_PROTOCOL{"PROTOCOL", SQL_INT, true};
constexpr auto TABLE_PACK_COLUMNS = make_array(COLUMN_RESOURCEPACK_PACK_ID, COLUMN_RESOURCEPACK_NAME, COLUMN_RESOURCEPACK_VERSION,
                                               COLUMN_RESOURCEPACK_CREATED, COLUMN_RESOURCEPACK_EXPIRED, COLUMN_RESOURCEPACK_PROTOCOL);

constexpr std::string_view TABLE_STATE_GAME = "GAME";
constexpr Column COLUMN_STATE_GAME_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_STATE_GAME_DAY{"DAY", SQL_INT};
constexpr Column COLUMN_STATE_GAME_PLAYER_TURN{"PLAYER_TURN", SQL_INT};
constexpr Column COLUMN_STATE_GAME_VARIANT{"VARIANT", SQL_SMALLSTRING};
constexpr Column COLUMN_STATE_GAME_VARIANTSTART{"VARIANTSTART", SQL_SMALLSTRING, true};
constexpr Column COLUMN_STATE_GAME_ACTIVE{"ACTIVE", SQL_BOOL};
constexpr Column COLUMN_STATE_GAME_HASH{"HASH", SQL_INT};
constexpr Column COLUMN_STATE_GAME_LANGUAGE{"LANGUAGE", SQL_SMALLSTRING, true};
constexpr auto TABLE_STATE_GAME_COLUMNS =
    make_array(COLUMN_STATE_GAME_ID, COLUMN_STATE_GAME_DAY, COLUMN_STATE_GAME_PLAYER_TURN, COLUMN_STATE_GAME_VARIANT, COLUMN_STATE_GAME_VARIANTSTART,
               COLUMN_STATE_GAME_ACTIVE, COLUMN_STATE_GAME_HASH, COLUMN_STATE_GAME_LANGUAGE);
constexpr std::string_view TABLE_STATE_GAME_PLAYERORDER = "GAME_PLAYERORDER_REFERENCE";
constexpr Column COLUMN_STATE_GAME_PLAYERORDER_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_STATE_GAME_PLAYERORDER_GAME_ID{"GAME_ID", SQL_INT};
constexpr Column COLUMN_STATE_GAME_PLAYERORDER_PLAYER{"PLAYER", SQL_INT};
constexpr Column COLUMN_STATE_GAME_PLAYERORDER_ORDER{"ORDER", SQL_INT};
constexpr auto TABLE_STATE_GAME_PLAYERORDER_COLUMNS = make_array(COLUMN_STATE_GAME_PLAYERORDER_ID, COLUMN_STATE_GAME_PLAYERORDER_GAME_ID,
                                                                 COLUMN_STATE_GAME_PLAYERORDER_PLAYER, COLUMN_STATE_GAME_PLAYERORDER_ORDER);
constexpr std::string_view TABLE_STATE_PLAYER = "PLAYER";
constexpr Column COLUMN_STATE_PLAYER_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_STATE_PLAYER_GAME_ID{"GAME_ID", SQL_INT};
constexpr Column COLUMN_STATE_PLAYER_USER{"USER", SQL_INT};
constexpr Column COLUMN_STATE_PLAYER_COMMANDER_NAME{"COMMANDER_NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_STATE_PLAYER_FUNDS{"FUNDS", SQL_INT};
constexpr Column COLUMN_STATE_PLAYER_POWER_CHARGE{"POWER_CHARGE", SQL_INT};
constexpr Column COLUMN_STATE_PLAYER_ARMY_COLOR{"ARMY_COLOR", SQL_SMALLSTRING};
constexpr Column COLUMN_STATE_PLAYER_ALIVE{"ALIVE", SQL_BOOL};
constexpr Column COLUMN_STATE_PLAYER_TOTAL_POWER_USES{"TOTAL_POWER_USES", SQL_INT};
constexpr Column COLUMN_STATE_PLAYER_UNIT_FACING{"UNIT_FACING", SQL_INT};
constexpr Column COLUMN_STATE_PLAYER_PLAYER_TYPE{"PLAYER_TYPE", SQL_SMALLSTRING};
constexpr Column COLUMN_STATE_PLAYER_TEAM{"TEAM", SQL_SMALLSTRING, true};
constexpr Column COLUMN_STATE_PLAYER_POWER_ACTIVE{"POWER_ACTIVE", SQL_SMALLSTRING, true};
constexpr Column COLUMN_STATE_PLAYER_POWER_ACTIVE_DAY{"POWER_ACTIVE_DAY", SQL_INT, true};
constexpr Column COLUMN_STATE_PLAYER_INCOME_MULTIPLIER{"INCOME_MULTIPLIER", SQL_INT, true};
constexpr Column COLUMN_STATE_PLAYER_CO_METER_MULTIPLIER{"CO_METER_MULTIPLIER", SQL_INT, true};
constexpr auto TABLE_STATE_PLAYER_COLUMNS = make_array(
    COLUMN_STATE_PLAYER_ID, COLUMN_STATE_PLAYER_GAME_ID, COLUMN_STATE_PLAYER_USER, COLUMN_STATE_PLAYER_COMMANDER_NAME, COLUMN_STATE_PLAYER_FUNDS,
    COLUMN_STATE_PLAYER_POWER_CHARGE, COLUMN_STATE_PLAYER_ARMY_COLOR, COLUMN_STATE_PLAYER_ALIVE, COLUMN_STATE_PLAYER_TOTAL_POWER_USES,
    COLUMN_STATE_PLAYER_UNIT_FACING, COLUMN_STATE_PLAYER_PLAYER_TYPE, COLUMN_STATE_PLAYER_TEAM, COLUMN_STATE_PLAYER_POWER_ACTIVE,
    COLUMN_STATE_PLAYER_POWER_ACTIVE_DAY, COLUMN_STATE_PLAYER_INCOME_MULTIPLIER, COLUMN_STATE_PLAYER_CO_METER_MULTIPLIER);
constexpr std::string_view TABLE_STATE_PLAYER_BANNEDUNITS = "PLAYER_BANNEDUNITS_REFERENCE";
constexpr Column COLUMN_STATE_PLAYER_BANNEDUNITS_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_STATE_PLAYER_BANNEDUNITS_GAME_ID{"GAME_ID", SQL_INT};
constexpr Column COLUMN_STATE_PLAYER_BANNEDUNITS_PLAYER_ID{"PLAYER_ID", SQL_INT};
constexpr Column COLUMN_STATE_PLAYER_BANNEDUNITS_UNIT_NAME{"UNIT_NAME", SQL_SMALLSTRING};
constexpr auto TABLE_STATE_PLAYER_BANNEDUNITS_COLUMNS =
    make_array(COLUMN_STATE_PLAYER_BANNEDUNITS_ID, COLUMN_STATE_PLAYER_BANNEDUNITS_GAME_ID, COLUMN_STATE_PLAYER_BANNEDUNITS_PLAYER_ID,
               COLUMN_STATE_PLAYER_BANNEDUNITS_UNIT_NAME);
constexpr std::string_view TABLE_STATE_UNIT = "UNIT";
constexpr Column COLUMN_STATE_UNIT_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_STATE_UNIT_GAME_ID{"GAME_ID", SQL_INT};
constexpr Column COLUMN_STATE_UNIT_X{"X", SQL_INT};
constexpr Column COLUMN_STATE_UNIT_Y{"Y", SQL_INT};
constexpr Column COLUMN_STATE_UNIT_NAME{"NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_STATE_UNIT_AMMO{"AMMO", SQL_INT};
constexpr Column COLUMN_STATE_UNIT_FUEL{"FUEL", SQL_INT};
constexpr Column COLUMN_STATE_UNIT_ACTIVE{"ACTIVE", SQL_BOOL};
constexpr Column COLUMN_STATE_UNIT_STUNNED{"STUNNED", SQL_INT, true};
constexpr Column COLUMN_STATE_UNIT_OWNER{"OWNER", SQL_INT, true};
constexpr Column COLUMN_STATE_UNIT_HIT_POINTS{"HIT_POINTS", SQL_INT};
constexpr Column COLUMN_STATE_UNIT_STEALTHED{"STEALTHED", SQL_BOOL, true};
constexpr Column COLUMN_STATE_UNIT_CURRENT_GOOD_LUCK{"CURRENT_GOOD_LUCK", SQL_DOUBLE};
constexpr Column COLUMN_STATE_UNIT_CURRENT_BAD_LUCK{"CURRENT_BAD_LUCK", SQL_DOUBLE};
constexpr Column COLUMN_STATE_UNIT_TRANSPORTED_BY{"TRANSPORTED_BY", SQL_INT, true};
constexpr Column COLUMN_STATE_UNIT_TRANSPORTED_SLOT{"TRANSPORTED_SLOT", SQL_INT, true};
constexpr auto TABLE_STATE_UNIT_COLUMNS =
    make_array(COLUMN_STATE_UNIT_ID, COLUMN_STATE_UNIT_GAME_ID, COLUMN_STATE_UNIT_X, COLUMN_STATE_UNIT_Y, COLUMN_STATE_UNIT_NAME,
               COLUMN_STATE_UNIT_AMMO, COLUMN_STATE_UNIT_FUEL, COLUMN_STATE_UNIT_ACTIVE, COLUMN_STATE_UNIT_STUNNED, COLUMN_STATE_UNIT_OWNER,
               COLUMN_STATE_UNIT_HIT_POINTS, COLUMN_STATE_UNIT_STEALTHED, COLUMN_STATE_UNIT_CURRENT_GOOD_LUCK, COLUMN_STATE_UNIT_CURRENT_BAD_LUCK,
               COLUMN_STATE_UNIT_TRANSPORTED_BY, COLUMN_STATE_UNIT_TRANSPORTED_SLOT);
constexpr std::string_view TABLE_STATE_UNIT_TRANSPORT = "UNIT_TRANSPORT_REFERENCE";
constexpr Column COLUMN_STATE_UNIT_TRANSPORT_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_STATE_UNIT_TRANSPORT_GAME_ID{"GAME_ID", SQL_INT};
constexpr Column COLUMN_STATE_UNIT_TRANSPORT_TRANSPORT_ID{"TRANSPORT_ID", SQL_INT};
constexpr Column COLUMN_STATE_UNIT_TRANSPORT_UNIT_ID{"UNIT_ID", SQL_INT};
constexpr Column COLUMN_STATE_UNIT_TRANSPORT_ORDER{"ORDER", SQL_INT};
constexpr auto TABLE_STATE_UNIT_TRANSPORT_COLUMNS =
    make_array(COLUMN_STATE_UNIT_TRANSPORT_ID, COLUMN_STATE_UNIT_TRANSPORT_GAME_ID, COLUMN_STATE_UNIT_TRANSPORT_TRANSPORT_ID,
               COLUMN_STATE_UNIT_TRANSPORT_UNIT_ID, COLUMN_STATE_UNIT_TRANSPORT_ORDER);
constexpr std::string_view TABLE_STATE_TERRAIN = "TERRAIN";
constexpr Column COLUMN_STATE_TERRAIN_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_STATE_TERRAIN_GAME_ID{"GAME_ID", SQL_INT};
constexpr Column COLUMN_STATE_TERRAIN_X{"X", SQL_INT};
constexpr Column COLUMN_STATE_TERRAIN_Y{"Y", SQL_INT};
constexpr Column COLUMN_STATE_TERRAIN_NAME{"NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_STATE_TERRAIN_ORIENTATION{"ORIENTATION", SQL_INT, true};
constexpr Column COLUMN_STATE_TERRAIN_CAPTURE_POINTS{"CAPTURE_POINTS", SQL_INT, true};
constexpr Column COLUMN_STATE_TERRAIN_ACTIVATION_COUNT{"ACTIVATION_COUNT", SQL_INT, true};
constexpr Column COLUMN_STATE_TERRAIN_OWNER{"OWNER", SQL_INT, true};
constexpr Column COLUMN_STATE_TERRAIN_HIT_POINTS{"HIT_POINTS", SQL_INT, true};
constexpr auto TABLE_STATE_TERRAIN_COLUMNS =
    make_array(COLUMN_STATE_TERRAIN_ID, COLUMN_STATE_TERRAIN_GAME_ID, COLUMN_STATE_TERRAIN_X, COLUMN_STATE_TERRAIN_Y, COLUMN_STATE_TERRAIN_NAME,
               COLUMN_STATE_TERRAIN_ORIENTATION, COLUMN_STATE_TERRAIN_CAPTURE_POINTS, COLUMN_STATE_TERRAIN_ACTIVATION_COUNT,
               COLUMN_STATE_TERRAIN_OWNER, COLUMN_STATE_TERRAIN_HIT_POINTS);
constexpr std::string_view TABLE_STATE_SETTINGS = "SETTINGS";
constexpr Column COLUMN_STATE_SETTINGS_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_STATE_SETTINGS_GAME_ID{"GAME_ID", SQL_INT};
constexpr Column COLUMN_STATE_SETTINGS_STARTING_FUNDS{"STARTING_FUNDS", SQL_INT};
constexpr Column COLUMN_STATE_SETTINGS_INCOME_MULTIPLIER{"INCOME_MULTIPLIER", SQL_INT};
constexpr Column COLUMN_STATE_SETTINGS_FOG_OF_WAR{"FOG_OF_WAR", SQL_BOOL};
constexpr Column COLUMN_STATE_SETTINGS_CO_POWERS{"CO_POWERS", SQL_BOOL};
constexpr Column COLUMN_STATE_SETTINGS_TEAMS{"TEAMS", SQL_BOOL};
constexpr Column COLUMN_STATE_SETTINGS_MOD_ID{"MOD_ID", SQL_INT};
constexpr Column COLUMN_STATE_SETTINGS_CO_METER_SIZE{"CO_METER_SIZE", SQL_INT};
constexpr Column COLUMN_STATE_SETTINGS_CO_METER_MULTIPLIER{"CO_METER_MULTIPLIER", SQL_INT};
constexpr Column COLUMN_STATE_SETTINGS_UNIT_LIMIT{"UNIT_LIMIT", SQL_INT, true};
constexpr Column COLUMN_STATE_SETTINGS_CAPTURE_LIMIT{"CAPTURE_LIMIT", SQL_INT, true};
constexpr Column COLUMN_STATE_SETTINGS_DAY_LIMIT{"DAY_LIMIT", SQL_INT, true};
constexpr auto TABLE_STATE_SETTINGS_COLUMNS =
    make_array(COLUMN_STATE_SETTINGS_ID, COLUMN_STATE_SETTINGS_GAME_ID, COLUMN_STATE_SETTINGS_STARTING_FUNDS, COLUMN_STATE_SETTINGS_INCOME_MULTIPLIER,
               COLUMN_STATE_SETTINGS_FOG_OF_WAR, COLUMN_STATE_SETTINGS_CO_POWERS, COLUMN_STATE_SETTINGS_TEAMS, COLUMN_STATE_SETTINGS_MOD_ID,
               COLUMN_STATE_SETTINGS_CO_METER_SIZE, COLUMN_STATE_SETTINGS_CO_METER_MULTIPLIER, COLUMN_STATE_SETTINGS_UNIT_LIMIT,
               COLUMN_STATE_SETTINGS_CAPTURE_LIMIT, COLUMN_STATE_SETTINGS_DAY_LIMIT);
constexpr std::string_view TABLE_STATE_SETTINGS_VARIANT = "SETTINGS_VARIANT_REFERENCE";
constexpr Column COLUMN_STATE_SETTINGS_VARIANT_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_STATE_SETTINGS_VARIANT_GAME_ID{"GAME_ID", SQL_INT};
constexpr Column COLUMN_STATE_SETTINGS_VARIANT_VARIANT{"VARIANT", SQL_SMALLSTRING};
constexpr Column COLUMN_STATE_SETTINGS_VARIANT_WEIGHT{"WEIGHT", SQL_INT};
constexpr auto TABLE_STATE_SETTINGS_VARIANT_COLUMNS = make_array(COLUMN_STATE_SETTINGS_VARIANT_ID, COLUMN_STATE_SETTINGS_VARIANT_GAME_ID,
                                                                 COLUMN_STATE_SETTINGS_VARIANT_VARIANT, COLUMN_STATE_SETTINGS_VARIANT_WEIGHT);

constexpr std::string_view TABLE_DATA_MOD = "MOD";
constexpr Column COLUMN_DATA_MOD_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_MOD_NAME{"NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_MOD_VERSION{"VERSION", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_MOD_EXPIRED{"EXPIRED", SQL_DATETIME, true};
constexpr auto TABLE_DATA_MOD_COLUMNS = make_array(COLUMN_DATA_MOD_ID, COLUMN_DATA_MOD_NAME, COLUMN_DATA_MOD_VERSION, COLUMN_DATA_MOD_EXPIRED);
constexpr std::string_view TABLE_DATA_MOD_DEFAULTPACK = "MOD_DEFAULTPACK_REFERENCE";
constexpr Column COLUMN_DATA_MOD_DEFAULTPACK_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_MOD_DEFAULTPACK_MOD_ID{"MOD_ID", SQL_INT};
constexpr Column COLUMN_DATA_MOD_DEFAULTPACK_NAME{"NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_MOD_DEFAULTPACK_ORDER{"ORDER", SQL_INT};
constexpr Column COLUMN_DATA_MOD_DEFAULTPACK_VERSION{"VERSION", SQL_SMALLSTRING, true};
constexpr auto TABLE_DATA_MOD_DEFAULTPACK_COLUMNS =
    make_array(COLUMN_DATA_MOD_DEFAULTPACK_ID, COLUMN_DATA_MOD_DEFAULTPACK_MOD_ID, COLUMN_DATA_MOD_DEFAULTPACK_NAME,
               COLUMN_DATA_MOD_DEFAULTPACK_ORDER, COLUMN_DATA_MOD_DEFAULTPACK_VERSION);

constexpr std::string_view TABLE_DATA_UNIT = "UNIT_TYPE";
constexpr Column COLUMN_DATA_UNIT_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_UNIT_MOD_ID{"MOD_ID", SQL_INT};
constexpr Column COLUMN_DATA_UNIT_NAME{"NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_UNIT_COST{"COST", SQL_INT};
constexpr Column COLUMN_DATA_UNIT_MAXFUEL{"MAXFUEL", SQL_INT};
constexpr Column COLUMN_DATA_UNIT_MAXAMMO{"MAXAMMO", SQL_INT};
constexpr Column COLUMN_DATA_UNIT_VISIONRANGE{"VISIONRANGE", SQL_INT};
constexpr Column COLUMN_DATA_UNIT_MOVEMENTCLASS{"MOVEMENTCLASS", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_UNIT_MOVEMENTRANGE{"MOVEMENTRANGE", SQL_INT};
constexpr Column COLUMN_DATA_UNIT_FUELPERDAY{"FUELPERDAY", SQL_INT, true};
constexpr Column COLUMN_DATA_UNIT_FUELPERDAYSTEALTH{"FUELPERDAYSTEALTH", SQL_INT, true};
constexpr Column COLUMN_DATA_UNIT_SUPPLYREPAIR{"SUPPLYREPAIR", SQL_INT, true};
constexpr Column COLUMN_DATA_UNIT_TRANSPORTCAPACITY{"TRANSPORTCAPACITY", SQL_INT, true};
constexpr Column COLUMN_DATA_UNIT_HITPOINTS{"HITPOINTS", SQL_INT, true};
constexpr Column COLUMN_DATA_UNIT_CAPTURESPEED{"CAPTURESPEED", SQL_INT, true};
constexpr Column COLUMN_DATA_UNIT_IGNORESVISIONOCCLUSION{"IGNORESVISIONOCCLUSION", SQL_BOOL, true};
constexpr Column COLUMN_DATA_UNIT_STEALTHTYPE{"STEALTHTYPE", SQL_SMALLSTRING, true};
constexpr Column COLUMN_DATA_UNIT_STATIONARYFIRE{"STATIONARYFIRE", SQL_BOOL, true};
constexpr auto TABLE_DATA_UNIT_COLUMNS = make_array(
    COLUMN_DATA_UNIT_ID, COLUMN_DATA_UNIT_MOD_ID, COLUMN_DATA_UNIT_NAME, COLUMN_DATA_UNIT_COST, COLUMN_DATA_UNIT_MAXFUEL, COLUMN_DATA_UNIT_MAXAMMO,
    COLUMN_DATA_UNIT_VISIONRANGE, COLUMN_DATA_UNIT_MOVEMENTCLASS, COLUMN_DATA_UNIT_MOVEMENTRANGE, COLUMN_DATA_UNIT_FUELPERDAY,
    COLUMN_DATA_UNIT_FUELPERDAYSTEALTH, COLUMN_DATA_UNIT_SUPPLYREPAIR, COLUMN_DATA_UNIT_TRANSPORTCAPACITY, COLUMN_DATA_UNIT_HITPOINTS,
    COLUMN_DATA_UNIT_CAPTURESPEED, COLUMN_DATA_UNIT_IGNORESVISIONOCCLUSION, COLUMN_DATA_UNIT_STEALTHTYPE, COLUMN_DATA_UNIT_STATIONARYFIRE);
constexpr std::string_view TABLE_DATA_UNIT_WEAPON = "UNIT_WEAPON_REFERENCE";
constexpr Column COLUMN_DATA_UNIT_WEAPON_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_UNIT_WEAPON_MOD_ID{"MOD_ID", SQL_INT};
constexpr Column COLUMN_DATA_UNIT_WEAPON_UNITNAME{"UNITTYPE_NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_UNIT_WEAPON_NAME{"WEAPONTYPE_NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_UNIT_WEAPON_ORDER{"WEAPONORDER", SQL_INT};
constexpr auto TABLE_DATA_UNIT_WEAPON_COLUMNS =
    make_array(COLUMN_DATA_UNIT_WEAPON_ID, COLUMN_DATA_UNIT_WEAPON_MOD_ID, COLUMN_DATA_UNIT_WEAPON_UNITNAME, COLUMN_DATA_UNIT_WEAPON_NAME,
               COLUMN_DATA_UNIT_WEAPON_ORDER);
constexpr std::string_view TABLE_DATA_UNIT_CLASSIFICATION = "UNIT_CLASSIFICATION_REFERENCE";
constexpr Column COLUMN_DATA_UNIT_CLASSIFICATION_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_UNIT_CLASSIFICATION_MOD_ID{"MOD_ID", SQL_INT};
constexpr Column COLUMN_DATA_UNIT_CLASSIFICATION_UNITNAME{"UNITTYPE_NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_UNIT_CLASSIFICATION_NAME{"CLASSIFICATION", SQL_SMALLSTRING};
constexpr auto TABLE_DATA_UNIT_CLASSIFICATION_COLUMNS = make_array(COLUMN_DATA_UNIT_CLASSIFICATION_ID, COLUMN_DATA_UNIT_CLASSIFICATION_MOD_ID,
                                                                   COLUMN_DATA_UNIT_CLASSIFICATION_UNITNAME, COLUMN_DATA_UNIT_CLASSIFICATION_NAME);
constexpr std::string_view TABLE_DATA_UNIT_TRANSPORT = "UNIT_TRANSPORTLIST_REFERENCE";
constexpr Column COLUMN_DATA_UNIT_TRANSPORT_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_UNIT_TRANSPORT_MOD_ID{"MOD_ID", SQL_INT};
constexpr Column COLUMN_DATA_UNIT_TRANSPORT_UNITNAME{"UNITTYPE_NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_UNIT_TRANSPORT_NAME{"TRANSPORTED_NAME", SQL_SMALLSTRING};
constexpr auto TABLE_DATA_UNIT_TRANSPORT_COLUMNS = make_array(COLUMN_DATA_UNIT_TRANSPORT_ID, COLUMN_DATA_UNIT_TRANSPORT_MOD_ID,
                                                              COLUMN_DATA_UNIT_TRANSPORT_UNITNAME, COLUMN_DATA_UNIT_TRANSPORT_NAME);

constexpr std::string_view TABLE_DATA_WEAPON = "WEAPON_TYPE";
constexpr Column COLUMN_DATA_WEAPON_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_WEAPON_MOD_ID{"MOD_ID", SQL_INT};
constexpr Column COLUMN_DATA_WEAPON_NAME{"NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_WEAPON_AMMOCONSUMED{"AMMOCONSUMED", SQL_INT};
constexpr Column COLUMN_DATA_WEAPON_MAXRANGE{"MAXRANGE", SQL_INT};
constexpr Column COLUMN_DATA_WEAPON_MINRANGE{"MINRANGE", SQL_INT, true};
constexpr Column COLUMN_DATA_WEAPON_SELFTARGET{"SELFTARGET", SQL_BOOL, true};
constexpr Column COLUMN_DATA_WEAPON_AFFECTEDBYLUCK{"AFFECTEDBYLUCK", SQL_BOOL, true};
constexpr Column COLUMN_DATA_WEAPON_NONLETHAL{"NONLETHAL", SQL_BOOL, true};
constexpr Column COLUMN_DATA_WEAPON_AREAOFEFFECT{"AREAOFEFFECT", SQL_INT, true};
constexpr Column COLUMN_DATA_WEAPON_FLATDAMAGE{"FLATDAMAGE", SQL_INT, true};
constexpr auto TABLE_DATA_WEAPON_COLUMNS =
    make_array(COLUMN_DATA_WEAPON_ID, COLUMN_DATA_WEAPON_MOD_ID, COLUMN_DATA_WEAPON_NAME, COLUMN_DATA_WEAPON_AMMOCONSUMED,
               COLUMN_DATA_WEAPON_MAXRANGE, COLUMN_DATA_WEAPON_MINRANGE, COLUMN_DATA_WEAPON_SELFTARGET, COLUMN_DATA_WEAPON_AFFECTEDBYLUCK,
               COLUMN_DATA_WEAPON_NONLETHAL, COLUMN_DATA_WEAPON_AREAOFEFFECT, COLUMN_DATA_WEAPON_FLATDAMAGE);
constexpr std::string_view TABLE_DATA_WEAPON_BASEDAMAGE = "WEAPON_BASEDAMAGE_REFERENCE";
constexpr Column COLUMN_DATA_WEAPON_BASEDAMAGE_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_WEAPON_BASEDAMAGE_MOD_ID{"MOD_ID", SQL_INT};
constexpr Column COLUMN_DATA_WEAPON_BASEDAMAGE_NAME{"WEAPONTYPE_NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_WEAPON_BASEDAMAGE_UNITNAME{"UNITTYPE_NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_WEAPON_BASEDAMAGE_DAMAGE{"DAMAGE", SQL_INT};
constexpr auto TABLE_DATA_WEAPON_BASEDAMAGE_COLUMNS =
    make_array(COLUMN_DATA_WEAPON_BASEDAMAGE_ID, COLUMN_DATA_WEAPON_BASEDAMAGE_MOD_ID, COLUMN_DATA_WEAPON_BASEDAMAGE_NAME,
               COLUMN_DATA_WEAPON_BASEDAMAGE_UNITNAME, COLUMN_DATA_WEAPON_BASEDAMAGE_DAMAGE);
constexpr std::string_view TABLE_DATA_WEAPON_STEALTHTARGET = "WEAPON_STEALTHTARGET_REFERENCE";
constexpr Column COLUMN_DATA_WEAPON_STEALTHTARGET_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_WEAPON_STEALTHTARGET_MOD_ID{"MOD_ID", SQL_INT};
constexpr Column COLUMN_DATA_WEAPON_STEALTHTARGET_WEAPON{"WEAPONTYPE_NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_WEAPON_STEALTHTARGET_STEALTHTYPE{"STEALTHTYPE", SQL_SMALLSTRING};
constexpr auto TABLE_DATA_WEAPON_STEALTHTARGET_COLUMNS =
    make_array(COLUMN_DATA_WEAPON_STEALTHTARGET_ID, COLUMN_DATA_WEAPON_STEALTHTARGET_MOD_ID, COLUMN_DATA_WEAPON_STEALTHTARGET_WEAPON,
               COLUMN_DATA_WEAPON_STEALTHTARGET_STEALTHTYPE);

constexpr std::string_view TABLE_DATA_TERRAIN = "TERRAIN_TYPE";
constexpr Column COLUMN_DATA_TERRAIN_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_TERRAIN_MOD_ID{"MOD_ID", SQL_INT};
constexpr Column COLUMN_DATA_TERRAIN_NAME{"NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_TERRAIN_STARS{"STARS", SQL_INT};
constexpr Column COLUMN_DATA_TERRAIN_MAXCAPTUREPOINTS{"MAXCAPTUREPOINTS", SQL_INT, true};
constexpr Column COLUMN_DATA_TERRAIN_SAMEAS{"SAMEAS", SQL_SMALLSTRING, true};
constexpr Column COLUMN_DATA_TERRAIN_INCOME{"INCOME", SQL_INT, true};
constexpr Column COLUMN_DATA_TERRAIN_REPAIR{"REPAIR", SQL_INT, true};
constexpr Column COLUMN_DATA_TERRAIN_OCCLUDESVISION{"OCCLUDESVISION", SQL_BOOL, true};
constexpr Column COLUMN_DATA_TERRAIN_HITPOINTS{"HITPOINTS", SQL_INT, true};
constexpr Column COLUMN_DATA_TERRAIN_DESTROYED{"DESTROYED", SQL_SMALLSTRING, true};
constexpr Column COLUMN_DATA_TERRAIN_DAMAGEDLIKE{"DAMAGEDLIKE", SQL_SMALLSTRING, true};
constexpr Column COLUMN_DATA_TERRAIN_ACTIVATIONMAX{"ACTIVATIONMAX", SQL_INT, true};
constexpr Column COLUMN_DATA_TERRAIN_ACTIVATIONCHANGE{"ACTIVATIONCHANGE", SQL_SMALLSTRING, true};
constexpr Column COLUMN_DATA_TERRAIN_LOSEIFCAPTURED{"LOSEIFCAPTURED", SQL_BOOL, true};
constexpr Column COLUMN_DATA_TERRAIN_LOSEIFALLCAPTURED{"LOSEIFALLCAPTURED", SQL_BOOL, true};
constexpr Column COLUMN_DATA_TERRAIN_DESTROYEDORIENTATION{"DESTROYEDORIENTATION", SQL_INT, true};
constexpr auto TABLE_DATA_TERRAIN_COLUMNS =
    make_array(COLUMN_DATA_TERRAIN_ID, COLUMN_DATA_TERRAIN_MOD_ID, COLUMN_DATA_TERRAIN_NAME, COLUMN_DATA_TERRAIN_STARS,
               COLUMN_DATA_TERRAIN_MAXCAPTUREPOINTS, COLUMN_DATA_TERRAIN_SAMEAS, COLUMN_DATA_TERRAIN_INCOME, COLUMN_DATA_TERRAIN_REPAIR,
               COLUMN_DATA_TERRAIN_OCCLUDESVISION, COLUMN_DATA_TERRAIN_HITPOINTS, COLUMN_DATA_TERRAIN_DESTROYED, COLUMN_DATA_TERRAIN_DAMAGEDLIKE,
               COLUMN_DATA_TERRAIN_ACTIVATIONMAX, COLUMN_DATA_TERRAIN_ACTIVATIONCHANGE, COLUMN_DATA_TERRAIN_LOSEIFCAPTURED,
               COLUMN_DATA_TERRAIN_LOSEIFALLCAPTURED, COLUMN_DATA_TERRAIN_DESTROYEDORIENTATION);
constexpr std::string_view TABLE_DATA_TERRAIN_BUILDREPAIR = "TERRAIN_BUILDREPAIR_REFERENCE";
constexpr Column COLUMN_DATA_TERRAIN_BUILDREPAIR_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_TERRAIN_BUILDREPAIR_MOD_ID{"MOD_ID", SQL_INT};
constexpr Column COLUMN_DATA_TERRAIN_BUILDREPAIR_TERRAIN_NAME{"TERRAINTYPE_NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_TERRAIN_BUILDREPAIR_UNIT_NAME{"UNITTYPE_NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_TERRAIN_BUILDREPAIR_UNIT_ORDER{"UNITORDER", SQL_INT, true};
constexpr Column COLUMN_DATA_TERRAIN_BUILDREPAIR_TYPE{"BUILDREPAIR", SQL_INT};
constexpr auto TABLE_DATA_TERRAIN_BUILDREPAIR_COLUMNS =
    make_array(COLUMN_DATA_TERRAIN_BUILDREPAIR_ID, COLUMN_DATA_TERRAIN_BUILDREPAIR_MOD_ID, COLUMN_DATA_TERRAIN_BUILDREPAIR_TERRAIN_NAME,
               COLUMN_DATA_TERRAIN_BUILDREPAIR_UNIT_NAME, COLUMN_DATA_TERRAIN_BUILDREPAIR_UNIT_ORDER, COLUMN_DATA_TERRAIN_BUILDREPAIR_TYPE);
constexpr std::string_view TABLE_DATA_TERRAIN_ACTIVATIONLIST = "TERRAIN_ACTIVATIONLIST_REFERENCE";
constexpr Column COLUMN_DATA_TERRAIN_ACTIVATIONLIST_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_TERRAIN_ACTIVATIONLIST_MOD_ID{"MOD_ID", SQL_INT};
constexpr Column COLUMN_DATA_TERRAIN_ACTIVATIONLIST_TERRAIN_NAME{"TERRAINTYPE_NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_TERRAIN_ACTIVATIONLIST_UNIT_NAME{"UNITTYPE_NAME", SQL_SMALLSTRING};
constexpr auto TABLE_DATA_TERRAIN_ACTIVATIONLIST_COLUMNS =
    make_array(COLUMN_DATA_TERRAIN_ACTIVATIONLIST_ID, COLUMN_DATA_TERRAIN_ACTIVATIONLIST_MOD_ID, COLUMN_DATA_TERRAIN_ACTIVATIONLIST_TERRAIN_NAME,
               COLUMN_DATA_TERRAIN_ACTIVATIONLIST_UNIT_NAME);
constexpr std::string_view TABLE_DATA_TERRAIN_ACTIVATIONEFFECT = "TERRAIN_ACTIVATIONEFFECT_REFERENCE";
constexpr Column COLUMN_DATA_TERRAIN_ACTIVATIONEFFECT_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_TERRAIN_ACTIVATIONEFFECT_MOD_ID{"MOD_ID", SQL_INT};
constexpr Column COLUMN_DATA_TERRAIN_ACTIVATIONEFFECT_TERRAIN_NAME{"TERRAINTYPE_NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_TERRAIN_ACTIVATIONEFFECT_EFFECT_TYPE{"EFFECT_TYPE", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_TERRAIN_ACTIVATIONEFFECT_EFFECT_NAME{"EFFECT_NAME", SQL_SMALLSTRING};
constexpr auto TABLE_DATA_TERRAIN_ACTIVATIONEFFECT_COLUMNS = make_array(
    COLUMN_DATA_TERRAIN_ACTIVATIONEFFECT_ID, COLUMN_DATA_TERRAIN_ACTIVATIONEFFECT_MOD_ID, COLUMN_DATA_TERRAIN_ACTIVATIONEFFECT_TERRAIN_NAME,
    COLUMN_DATA_TERRAIN_ACTIVATIONEFFECT_EFFECT_TYPE, COLUMN_DATA_TERRAIN_ACTIVATIONEFFECT_EFFECT_NAME);

constexpr std::string_view TABLE_DATA_COMMANDER = "COMMANDER_TYPE";
constexpr Column COLUMN_DATA_COMMANDER_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_COMMANDER_MOD_ID{"MOD_ID", SQL_INT};
constexpr Column COLUMN_DATA_COMMANDER_NAME{"NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_COMMANDER_COPCOST{"COPCOST", SQL_INT, true};
constexpr Column COLUMN_DATA_COMMANDER_SCOPCOST{"SCOPCOST", SQL_INT, true};
constexpr Column COLUMN_DATA_COMMANDER_COMETERMULTIPLIER{"COMETERMULTIPLIER", SQL_INT, true};
constexpr Column COLUMN_DATA_COMMANDER_PLAYABLE{"PLAYABLE", SQL_BOOL, true};
constexpr auto TABLE_DATA_COMMANDER_COLUMNS =
    make_array(COLUMN_DATA_COMMANDER_ID, COLUMN_DATA_COMMANDER_MOD_ID, COLUMN_DATA_COMMANDER_NAME, COLUMN_DATA_COMMANDER_COPCOST,
               COLUMN_DATA_COMMANDER_SCOPCOST, COLUMN_DATA_COMMANDER_COMETERMULTIPLIER, COLUMN_DATA_COMMANDER_PLAYABLE);
constexpr std::string_view TABLE_DATA_COMMANDER_EFFECT = "COMMANDER_EFFECT_REFERENCE";
constexpr Column COLUMN_DATA_COMMANDER_EFFECT_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_COMMANDER_EFFECT_MOD_ID{"MOD_ID", SQL_INT};
constexpr Column COLUMN_DATA_COMMANDER_EFFECT_COMMANDER_NAME{"COMMANDER_NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_COMMANDER_EFFECT_NAME{"EFFECT_NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_COMMANDER_EFFECT_TYPE{"EFFECT_TYPE", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_COMMANDER_EFFECT_CATEGORY{"EFFECT_CATEGORY", SQL_INT};
constexpr auto TABLE_DATA_COMMANDER_EFFECT_COLUMNS =
    make_array(COLUMN_DATA_COMMANDER_EFFECT_ID, COLUMN_DATA_COMMANDER_EFFECT_MOD_ID, COLUMN_DATA_COMMANDER_EFFECT_COMMANDER_NAME,
               COLUMN_DATA_COMMANDER_EFFECT_NAME, COLUMN_DATA_COMMANDER_EFFECT_TYPE, COLUMN_DATA_COMMANDER_EFFECT_CATEGORY);

constexpr std::string_view TABLE_DATA_MOVEMENT = "MOVEMENT_TYPE";
constexpr Column COLUMN_DATA_MOVEMENT_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_MOVEMENT_MOD_ID{"MOD_ID", SQL_INT};
constexpr Column COLUMN_DATA_MOVEMENT_NAME{"NAME", SQL_SMALLSTRING};
constexpr auto TABLE_DATA_MOVEMENT_COLUMNS = make_array(COLUMN_DATA_MOVEMENT_ID, COLUMN_DATA_MOVEMENT_MOD_ID, COLUMN_DATA_MOVEMENT_NAME);
constexpr std::string_view TABLE_DATA_MOVEMENT_COST = "MOVEMENT_COST_REFERENCE";
constexpr Column COLUMN_DATA_MOVEMENT_COST_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_MOVEMENT_COST_MOD_ID{"MOD_ID", SQL_INT};
constexpr Column COLUMN_DATA_MOVEMENT_COST_NAME{"MOVEMENT_NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_MOVEMENT_COST_TERRAIN{"TERRAINTYPE_NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_MOVEMENT_COST_COST{"COST", SQL_INT};
constexpr Column COLUMN_DATA_MOVEMENT_COST_VARIANT{"VARIANT", SQL_SMALLSTRING, true};
constexpr auto TABLE_DATA_MOVEMENT_COST_COLUMNS =
    make_array(COLUMN_DATA_MOVEMENT_COST_ID, COLUMN_DATA_MOVEMENT_COST_MOD_ID, COLUMN_DATA_MOVEMENT_COST_NAME, COLUMN_DATA_MOVEMENT_COST_TERRAIN,
               COLUMN_DATA_MOVEMENT_COST_COST, COLUMN_DATA_MOVEMENT_COST_VARIANT);
constexpr std::string_view TABLE_DATA_MOVEMENT_RULE_REF = "MOVEMENT_RULE_REFERENCE";
constexpr Column COLUMN_DATA_MOVEMENT_RULE_REF_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_MOVEMENT_RULE_REF_MOD_ID{"MOD_ID", SQL_INT};
constexpr Column COLUMN_DATA_MOVEMENT_RULE_REF_NAME{"MOVEMENT_NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_MOVEMENT_RULE_REF_RULE{"RULE_NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_MOVEMENT_RULE_REF_ORDER{"ORDER", SQL_INT};
constexpr auto TABLE_DATA_MOVEMENT_RULE_REF_COLUMNS =
    make_array(COLUMN_DATA_MOVEMENT_RULE_REF_ID, COLUMN_DATA_MOVEMENT_RULE_REF_MOD_ID, COLUMN_DATA_MOVEMENT_RULE_REF_NAME,
               COLUMN_DATA_MOVEMENT_RULE_REF_RULE, COLUMN_DATA_MOVEMENT_RULE_REF_ORDER);

constexpr std::string_view TABLE_DATA_MOVEMENT_RULE = "MOVEMENT_RULE";
constexpr Column COLUMN_DATA_MOVEMENT_RULE_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_MOVEMENT_RULE_MOD_ID{"MOD_ID", SQL_INT};
constexpr Column COLUMN_DATA_MOVEMENT_RULE_NAME{"NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_MOVEMENT_RULE_TYPE{"TYPE", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_MOVEMENT_RULE_MAXREPEAT{"MAXREPEAT", SQL_INT};
constexpr Column COLUMN_DATA_MOVEMENT_RULE_CONFIRMTYPE{"CONFIRMTYPE", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_MOVEMENT_RULE_STOPIFUSED{"STOPIFUSED", SQL_BOOL};
constexpr auto TABLE_DATA_MOVEMENT_RULE_COLUMNS =
    make_array(COLUMN_DATA_MOVEMENT_RULE_ID, COLUMN_DATA_MOVEMENT_RULE_MOD_ID, COLUMN_DATA_MOVEMENT_RULE_NAME, COLUMN_DATA_MOVEMENT_RULE_TYPE,
               COLUMN_DATA_MOVEMENT_RULE_MAXREPEAT, COLUMN_DATA_MOVEMENT_RULE_CONFIRMTYPE, COLUMN_DATA_MOVEMENT_RULE_STOPIFUSED);

constexpr std::string_view TABLE_DATA_PLAYER = "PLAYER_TYPE";
constexpr Column COLUMN_DATA_PLAYER_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_PLAYER_MOD_ID{"MOD_ID", SQL_INT};
constexpr Column COLUMN_DATA_PLAYER_NAME{"NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_PLAYER_COMMANDERMOD{"COMMANDERTYPEMOD", SQL_SMALLSTRING, true};
constexpr Column COLUMN_DATA_PLAYER_TEAM{"TEAMNAME", SQL_SMALLSTRING, true};
constexpr auto TABLE_DATA_PLAYER_COLUMNS =
    make_array(COLUMN_DATA_PLAYER_ID, COLUMN_DATA_PLAYER_MOD_ID, COLUMN_DATA_PLAYER_NAME, COLUMN_DATA_PLAYER_COMMANDERMOD, COLUMN_DATA_PLAYER_TEAM);
constexpr std::string_view TABLE_DATA_PLAYER_PERMITTEDPLAYERSLOT = "PLAYER_PERMITTEDPLAYERSLOT_REFERENCE";
constexpr Column COLUMN_DATA_PLAYER_PERMITTEDPLAYERSLOT_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_PLAYER_PERMITTEDPLAYERSLOT_MOD_ID{"MOD_ID", SQL_INT};
constexpr Column COLUMN_DATA_PLAYER_PERMITTEDPLAYERSLOT_NAME{"PLAYERTYPE_NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_PLAYER_PERMITTEDPLAYERSLOT_SLOT{"PERMITTEDPLAYERSLOT", SQL_SMALLSTRING};
constexpr auto TABLE_DATA_PLAYER_PERMITTEDPLAYERSLOT_COLUMNS =
    make_array(COLUMN_DATA_PLAYER_PERMITTEDPLAYERSLOT_ID, COLUMN_DATA_PLAYER_PERMITTEDPLAYERSLOT_MOD_ID, COLUMN_DATA_PLAYER_PERMITTEDPLAYERSLOT_NAME,
               COLUMN_DATA_PLAYER_PERMITTEDPLAYERSLOT_SLOT);
constexpr std::string_view TABLE_DATA_PLAYER_PERMITTEDCOMMANDERTYPE = "PLAYER_PERMITTEDCOMMANDERTYPE_REFERENCE";
constexpr Column COLUMN_DATA_PLAYER_PERMITTEDCOMMANDERTYPE_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_PLAYER_PERMITTEDCOMMANDERTYPE_MOD_ID{"MOD_ID", SQL_INT};
constexpr Column COLUMN_DATA_PLAYER_PERMITTEDCOMMANDERTYPE_NAME{"PLAYERTYPE_NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_PLAYER_PERMITTEDCOMMANDERTYPE_COMMANDER{"PERMITTEDCOMMANDERTYPE", SQL_SMALLSTRING};
constexpr auto TABLE_DATA_PLAYER_PERMITTEDCOMMANDERTYPE_COLUMNS =
    make_array(COLUMN_DATA_PLAYER_PERMITTEDCOMMANDERTYPE_ID, COLUMN_DATA_PLAYER_PERMITTEDCOMMANDERTYPE_MOD_ID,
               COLUMN_DATA_PLAYER_PERMITTEDCOMMANDERTYPE_NAME, COLUMN_DATA_PLAYER_PERMITTEDCOMMANDERTYPE_COMMANDER);

constexpr std::string_view TABLE_DATA_EFFECT_TARGET = "EFFECT_TARGET_REFERENCE";
constexpr Column COLUMN_DATA_EFFECT_TARGET_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_EFFECT_TARGET_MOD_ID{"MOD_ID", SQL_INT};
constexpr Column COLUMN_DATA_EFFECT_TARGET_EFFECT_NAME{"EFFECT_NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_EFFECT_TARGET_TYPE{"EFFECT_TYPE", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_EFFECT_TARGET_TARGET{"TARGET", SQL_SMALLSTRING};
constexpr auto TABLE_DATA_EFFECT_TARGET_COLUMNS =
    make_array(COLUMN_DATA_EFFECT_TARGET_ID, COLUMN_DATA_EFFECT_TARGET_MOD_ID, COLUMN_DATA_EFFECT_TARGET_EFFECT_NAME, COLUMN_DATA_EFFECT_TARGET_TYPE,
               COLUMN_DATA_EFFECT_TARGET_TARGET);
constexpr std::string_view TABLE_DATA_EFFECT_AFFECT = "EFFECT_AFFECT_REFERENCE";
constexpr Column COLUMN_DATA_EFFECT_AFFECT_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_EFFECT_AFFECT_MOD_ID{"MOD_ID", SQL_INT};
constexpr Column COLUMN_DATA_EFFECT_AFFECT_EFFECT_NAME{"EFFECT_NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_EFFECT_AFFECT_TYPE{"EFFECT_TYPE", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_EFFECT_AFFECT_AFFECTS{"AFFECTS", SQL_SMALLSTRING};
constexpr auto TABLE_DATA_EFFECT_AFFECT_COLUMNS =
    make_array(COLUMN_DATA_EFFECT_AFFECT_ID, COLUMN_DATA_EFFECT_AFFECT_MOD_ID, COLUMN_DATA_EFFECT_AFFECT_EFFECT_NAME, COLUMN_DATA_EFFECT_AFFECT_TYPE,
               COLUMN_DATA_EFFECT_AFFECT_AFFECTS);
constexpr std::string_view TABLE_DATA_EFFECT_CLASSIFICATION = "EFFECT_CLASSIFICATION_REFERENCE";
constexpr Column COLUMN_DATA_EFFECT_CLASSIFICATION_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_EFFECT_CLASSIFICATION_MOD_ID{"MOD_ID", SQL_INT};
constexpr Column COLUMN_DATA_EFFECT_CLASSIFICATION_EFFECT_NAME{"EFFECT_NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_EFFECT_CLASSIFICATION_TYPE{"EFFECT_TYPE", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_EFFECT_CLASSIFICATION_CLASSIFICATION{"CLASSIFICATION", SQL_SMALLSTRING};
constexpr auto TABLE_DATA_EFFECT_CLASSIFICATION_COLUMNS =
    make_array(COLUMN_DATA_EFFECT_CLASSIFICATION_ID, COLUMN_DATA_EFFECT_CLASSIFICATION_MOD_ID, COLUMN_DATA_EFFECT_CLASSIFICATION_EFFECT_NAME,
               COLUMN_DATA_EFFECT_CLASSIFICATION_TYPE, COLUMN_DATA_EFFECT_CLASSIFICATION_CLASSIFICATION);
constexpr std::string_view TABLE_DATA_EFFECT_TERRAIN = "EFFECT_TERRAIN_REFERENCE";
constexpr Column COLUMN_DATA_EFFECT_TERRAIN_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_EFFECT_TERRAIN_MOD_ID{"MOD_ID", SQL_INT};
constexpr Column COLUMN_DATA_EFFECT_TERRAIN_EFFECT_NAME{"EFFECT_NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_EFFECT_TERRAIN_TYPE{"EFFECT_TYPE", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_EFFECT_TERRAIN_TERRAIN{"TERRAINTYPE_NAME", SQL_SMALLSTRING};
constexpr auto TABLE_DATA_EFFECT_TERRAIN_COLUMNS =
    make_array(COLUMN_DATA_EFFECT_TERRAIN_ID, COLUMN_DATA_EFFECT_TERRAIN_MOD_ID, COLUMN_DATA_EFFECT_TERRAIN_EFFECT_NAME,
               COLUMN_DATA_EFFECT_TERRAIN_TYPE, COLUMN_DATA_EFFECT_TERRAIN_TERRAIN);
constexpr std::string_view TABLE_DATA_EFFECT_UNITTYPEREQUIRED = "EFFECT_UNITTYPEREQUIRED_REFERENCE";
constexpr Column COLUMN_DATA_EFFECT_UNITTYPEREQUIRED_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_EFFECT_UNITTYPEREQUIRED_MOD_ID{"MOD_ID", SQL_INT};
constexpr Column COLUMN_DATA_EFFECT_UNITTYPEREQUIRED_EFFECT_NAME{"EFFECT_NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_EFFECT_UNITTYPEREQUIRED_TYPE{"EFFECT_TYPE", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_EFFECT_UNITTYPEREQUIRED_UNIT{"UNITTYPE_NAME", SQL_SMALLSTRING};
constexpr auto TABLE_DATA_EFFECT_UNITTYPEREQUIRED_COLUMNS =
    make_array(COLUMN_DATA_EFFECT_UNITTYPEREQUIRED_ID, COLUMN_DATA_EFFECT_UNITTYPEREQUIRED_MOD_ID, COLUMN_DATA_EFFECT_UNITTYPEREQUIRED_EFFECT_NAME,
               COLUMN_DATA_EFFECT_UNITTYPEREQUIRED_TYPE, COLUMN_DATA_EFFECT_UNITTYPEREQUIRED_UNIT);

constexpr std::string_view TABLE_DATA_PASSIVE_UNIT_EFFECT = "PASSIVE_UNIT_EFFECT";
constexpr Column COLUMN_DATA_PASSIVE_UNIT_EFFECT_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_PASSIVE_UNIT_EFFECT_MOD_ID{"MOD_ID", SQL_INT};
constexpr Column COLUMN_DATA_PASSIVE_UNIT_EFFECT_NAME{"NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_PASSIVE_UNIT_EFFECT_FIREPOWER{"FIREPOWERMOD", SQL_INT, true};
constexpr Column COLUMN_DATA_PASSIVE_UNIT_EFFECT_DEFENSE{"DEFENSEMOD", SQL_INT, true};
constexpr Column COLUMN_DATA_PASSIVE_UNIT_EFFECT_INDIRECTDEFENSE{"INDIRECTDEFENSEMOD", SQL_INT, true};
constexpr Column COLUMN_DATA_PASSIVE_UNIT_EFFECT_MINRANGE{"MINRANGEMOD", SQL_INT, true};
constexpr Column COLUMN_DATA_PASSIVE_UNIT_EFFECT_MAXRANGE{"MAXRANGEMOD", SQL_INT, true};
constexpr Column COLUMN_DATA_PASSIVE_UNIT_EFFECT_FUELUSE{"FUELUSEMOD", SQL_INT, true};
constexpr Column COLUMN_DATA_PASSIVE_UNIT_EFFECT_AMMOUSE{"AMMOUSEMOD", SQL_INT, true};
constexpr Column COLUMN_DATA_PASSIVE_UNIT_EFFECT_GOODLUCK{"GOODLUCKMOD", SQL_INT, true};
constexpr Column COLUMN_DATA_PASSIVE_UNIT_EFFECT_BADLUCK{"BADLUCKMOD", SQL_INT, true};
constexpr Column COLUMN_DATA_PASSIVE_UNIT_EFFECT_MOVEMENT{"MOVEMENTMOD", SQL_INT, true};
constexpr Column COLUMN_DATA_PASSIVE_UNIT_EFFECT_VISION{"VISIONMOD", SQL_INT, true};
constexpr Column COLUMN_DATA_PASSIVE_UNIT_EFFECT_TERRAINSTARS{"TERRAINSTARSMOD", SQL_INT, true};
constexpr Column COLUMN_DATA_PASSIVE_UNIT_EFFECT_TERRAINSTARSFLAT{"TERRAINSTARSFLATMOD", SQL_INT, true};
constexpr Column COLUMN_DATA_PASSIVE_UNIT_EFFECT_TERRAINDEFENSE{"TERRAINSTARSDEFENSE", SQL_INT, true};
constexpr Column COLUMN_DATA_PASSIVE_UNIT_EFFECT_TERRAINFIREPOWER{"TERRAINSTARSFIREPOWER", SQL_INT, true};
constexpr Column COLUMN_DATA_PASSIVE_UNIT_EFFECT_COUNTERFIRE{"COUNTERFIREMOD", SQL_INT, true};
constexpr Column COLUMN_DATA_PASSIVE_UNIT_EFFECT_COUNTERFIRST{"COUNTERFIRST", SQL_BOOL, true};
constexpr Column COLUMN_DATA_PASSIVE_UNIT_EFFECT_CAPTURERATE{"CAPTURERATEMOD", SQL_INT, true};
constexpr Column COLUMN_DATA_PASSIVE_UNIT_EFFECT_UNITCOST{"UNITCOSTMOD", SQL_INT, true};
constexpr Column COLUMN_DATA_PASSIVE_UNIT_EFFECT_FIREPOWERFROMFUNDS{"FIREPOWERFROMFUNDS", SQL_INT, true};
constexpr Column COLUMN_DATA_PASSIVE_UNIT_EFFECT_DEFENSEFROMFUNDS{"DEFENSEFROMFUNDS", SQL_INT, true};
constexpr Column COLUMN_DATA_PASSIVE_UNIT_EFFECT_FUNDSFROMDAMAGE{"FUNDSFROMDAMAGE", SQL_INT, true};
constexpr Column COLUMN_DATA_PASSIVE_UNIT_EFFECT_COMETERCHARGEFROMDEALTDAMAGE{"COMETERCHARGEFROMDEALTDAMAGE", SQL_INT, true};
constexpr Column COLUMN_DATA_PASSIVE_UNIT_EFFECT_COMETERCHARGEFROMRECEIVEDDAMAGE{"COMETERCHARGEFROMRECEIVEDDAMAGE", SQL_INT, true};
constexpr Column COLUMN_DATA_PASSIVE_UNIT_EFFECT_TERRAINSTARSFLATDEFENSE{"TERRAINSTARSFLATDEFENSE", SQL_INT, true};
constexpr Column COLUMN_DATA_PASSIVE_UNIT_EFFECT_TERRAINSTARSFLATFIREPOWER{"TERRAINSTARSFLATFIREPOWER", SQL_INT, true};
constexpr auto TABLE_DATA_PUE_COLUMNS = make_array(
    COLUMN_DATA_PASSIVE_UNIT_EFFECT_ID, COLUMN_DATA_PASSIVE_UNIT_EFFECT_MOD_ID, COLUMN_DATA_PASSIVE_UNIT_EFFECT_NAME,
    COLUMN_DATA_PASSIVE_UNIT_EFFECT_FIREPOWER, COLUMN_DATA_PASSIVE_UNIT_EFFECT_DEFENSE, COLUMN_DATA_PASSIVE_UNIT_EFFECT_INDIRECTDEFENSE,
    COLUMN_DATA_PASSIVE_UNIT_EFFECT_MINRANGE, COLUMN_DATA_PASSIVE_UNIT_EFFECT_MAXRANGE, COLUMN_DATA_PASSIVE_UNIT_EFFECT_FUELUSE,
    COLUMN_DATA_PASSIVE_UNIT_EFFECT_AMMOUSE, COLUMN_DATA_PASSIVE_UNIT_EFFECT_GOODLUCK, COLUMN_DATA_PASSIVE_UNIT_EFFECT_BADLUCK,
    COLUMN_DATA_PASSIVE_UNIT_EFFECT_MOVEMENT, COLUMN_DATA_PASSIVE_UNIT_EFFECT_VISION, COLUMN_DATA_PASSIVE_UNIT_EFFECT_TERRAINSTARS,
    COLUMN_DATA_PASSIVE_UNIT_EFFECT_TERRAINSTARSFLAT, COLUMN_DATA_PASSIVE_UNIT_EFFECT_TERRAINDEFENSE,
    COLUMN_DATA_PASSIVE_UNIT_EFFECT_TERRAINFIREPOWER, COLUMN_DATA_PASSIVE_UNIT_EFFECT_COUNTERFIRE, COLUMN_DATA_PASSIVE_UNIT_EFFECT_COUNTERFIRST,
    COLUMN_DATA_PASSIVE_UNIT_EFFECT_CAPTURERATE, COLUMN_DATA_PASSIVE_UNIT_EFFECT_UNITCOST, COLUMN_DATA_PASSIVE_UNIT_EFFECT_FIREPOWERFROMFUNDS,
    COLUMN_DATA_PASSIVE_UNIT_EFFECT_DEFENSEFROMFUNDS, COLUMN_DATA_PASSIVE_UNIT_EFFECT_FUNDSFROMDAMAGE,
    COLUMN_DATA_PASSIVE_UNIT_EFFECT_COMETERCHARGEFROMDEALTDAMAGE, COLUMN_DATA_PASSIVE_UNIT_EFFECT_COMETERCHARGEFROMRECEIVEDDAMAGE,
    COLUMN_DATA_PASSIVE_UNIT_EFFECT_TERRAINSTARSFLATDEFENSE, COLUMN_DATA_PASSIVE_UNIT_EFFECT_TERRAINSTARSFLATFIREPOWER);
constexpr std::string_view TABLE_DATA_PUE_FIREPOWERFROMTERRAIN = "PUE_FIREPOWERFROMTERRAIN_REFERENCE";
constexpr Column COLUMN_DATA_PUE_FIREPOWERFROMTERRAIN_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_PUE_FIREPOWERFROMTERRAIN_MOD_ID{"MOD_ID", SQL_INT};
constexpr Column COLUMN_DATA_PUE_FIREPOWERFROMTERRAIN_EFFECT_NAME{"EFFECT_NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_PUE_FIREPOWERFROMTERRAIN_TERRAIN{"TERRAINTYPE_NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_PUE_FIREPOWERFROMTERRAIN_FIREPOWER{"FIREPOWERMOD", SQL_INT};
constexpr auto TABLE_DATA_PUE_FIREPOWERFROMTERRAIN_COLUMNS =
    make_array(COLUMN_DATA_PUE_FIREPOWERFROMTERRAIN_ID, COLUMN_DATA_PUE_FIREPOWERFROMTERRAIN_MOD_ID, COLUMN_DATA_PUE_FIREPOWERFROMTERRAIN_EFFECT_NAME,
               COLUMN_DATA_PUE_FIREPOWERFROMTERRAIN_TERRAIN, COLUMN_DATA_PUE_FIREPOWERFROMTERRAIN_FIREPOWER);
constexpr std::string_view TABLE_DATA_PUE_DEFENSEFROMTERRAIN = "PUE_DEFENSEFROMTERRAIN_REFERENCE";
constexpr Column COLUMN_DATA_PUE_DEFENSEFROMTERRAIN_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_PUE_DEFENSEFROMTERRAIN_MOD_ID{"MOD_ID", SQL_INT};
constexpr Column COLUMN_DATA_PUE_DEFENSEFROMTERRAIN_EFFECT_NAME{"EFFECT_NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_PUE_DEFENSEFROMTERRAIN_TERRAIN{"TERRAINTYPE_NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_PUE_DEFENSEFROMTERRAIN_DEFENSE{"DEFENSEMOD", SQL_INT};
constexpr auto TABLE_DATA_PUE_DEFENSEFROMTERRAIN_COLUMNS =
    make_array(COLUMN_DATA_PUE_DEFENSEFROMTERRAIN_ID, COLUMN_DATA_PUE_DEFENSEFROMTERRAIN_MOD_ID, COLUMN_DATA_PUE_DEFENSEFROMTERRAIN_EFFECT_NAME,
               COLUMN_DATA_PUE_DEFENSEFROMTERRAIN_TERRAIN, COLUMN_DATA_PUE_DEFENSEFROMTERRAIN_DEFENSE);
constexpr std::string_view TABLE_DATA_PUE_VISIONVARIANT = "PUE_VISIONVARIANT_REFERENCE";
constexpr Column COLUMN_DATA_PUE_VISIONVARIANT_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_PUE_VISIONVARIANT_MOD_ID{"MOD_ID", SQL_INT};
constexpr Column COLUMN_DATA_PUE_VISIONVARIANT_EFFECT_NAME{"EFFECT_NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_PUE_VISIONVARIANT_VARIANT{"VARIANT", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_PUE_VISIONVARIANT_VISION{"VISIONMOD", SQL_INT};
constexpr auto TABLE_DATA_PUE_VISIONVARIANT_COLUMNS =
    make_array(COLUMN_DATA_PUE_VISIONVARIANT_ID, COLUMN_DATA_PUE_VISIONVARIANT_MOD_ID, COLUMN_DATA_PUE_VISIONVARIANT_EFFECT_NAME,
               COLUMN_DATA_PUE_VISIONVARIANT_VARIANT, COLUMN_DATA_PUE_VISIONVARIANT_VISION);
constexpr std::string_view TABLE_DATA_PUE_FIREPOWERVARIANT = "PUE_FIREPOWERVARIANT_REFERENCE";
constexpr Column COLUMN_DATA_PUE_FIREPOWERVARIANT_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_PUE_FIREPOWERVARIANT_MOD_ID{"MOD_ID", SQL_INT};
constexpr Column COLUMN_DATA_PUE_FIREPOWERVARIANT_EFFECT_NAME{"EFFECT_NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_PUE_FIREPOWERVARIANT_VARIANT{"VARIANT", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_PUE_FIREPOWERVARIANT_FIREPOWER{"FIREPOWERMOD", SQL_INT};
constexpr auto TABLE_DATA_PUE_FIREPOWERVARIANT_COLUMNS =
    make_array(COLUMN_DATA_PUE_FIREPOWERVARIANT_ID, COLUMN_DATA_PUE_FIREPOWERVARIANT_MOD_ID, COLUMN_DATA_PUE_FIREPOWERVARIANT_EFFECT_NAME,
               COLUMN_DATA_PUE_FIREPOWERVARIANT_VARIANT, COLUMN_DATA_PUE_FIREPOWERVARIANT_FIREPOWER);
constexpr std::string_view TABLE_DATA_PUE_DEFENSEVARIANT = "PUE_DEFENSEVARIANT_REFERENCE";
constexpr Column COLUMN_DATA_PUE_DEFENSEVARIANT_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_PUE_DEFENSEVARIANT_MOD_ID{"MOD_ID", SQL_INT};
constexpr Column COLUMN_DATA_PUE_DEFENSEVARIANT_EFFECT_NAME{"EFFECT_NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_PUE_DEFENSEVARIANT_VARIANT{"VARIANT", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_PUE_DEFENSEVARIANT_DEFENSE{"DEFENSEMOD", SQL_INT};
constexpr auto TABLE_DATA_PUE_DEFENSEVARIANT_COLUMNS =
    make_array(COLUMN_DATA_PUE_DEFENSEVARIANT_ID, COLUMN_DATA_PUE_DEFENSEVARIANT_MOD_ID, COLUMN_DATA_PUE_DEFENSEVARIANT_EFFECT_NAME,
               COLUMN_DATA_PUE_DEFENSEVARIANT_VARIANT, COLUMN_DATA_PUE_DEFENSEVARIANT_DEFENSE);
constexpr std::string_view TABLE_DATA_PUE_INTEL = "PUE_INTEL_REFERENCE";
constexpr Column COLUMN_DATA_PUE_INTEL_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_PUE_INTEL_MOD_ID{"MOD_ID", SQL_INT};
constexpr Column COLUMN_DATA_PUE_INTEL_EFFECT_NAME{"EFFECT_NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_PUE_INTEL_TYPE{"INTEL_TYPE", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_PUE_INTEL_TARGET{"TARGET", SQL_SMALLSTRING};
constexpr auto TABLE_DATA_PUE_INTEL_COLUMNS = make_array(COLUMN_DATA_PUE_INTEL_ID, COLUMN_DATA_PUE_INTEL_MOD_ID, COLUMN_DATA_PUE_INTEL_EFFECT_NAME,
                                                         COLUMN_DATA_PUE_INTEL_TYPE, COLUMN_DATA_PUE_INTEL_TARGET);

constexpr std::string_view TABLE_DATA_ACTIVE_UNIT_EFFECT = "ACTIVE_UNIT_EFFECT";
constexpr Column COLUMN_DATA_ACTIVE_UNIT_EFFECT_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_ACTIVE_UNIT_EFFECT_MOD_ID{"MOD_ID", SQL_INT};
constexpr Column COLUMN_DATA_ACTIVE_UNIT_EFFECT_NAME{"NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_ACTIVE_UNIT_EFFECT_HITPOINT{"HITPOINTMOD", SQL_INT, true};
constexpr Column COLUMN_DATA_ACTIVE_UNIT_EFFECT_ROUNDHITPOINT{"ROUNDHITPOINTS", SQL_INT, true};
constexpr Column COLUMN_DATA_ACTIVE_UNIT_EFFECT_SETFUEL{"SETFUEL", SQL_INT, true};
constexpr Column COLUMN_DATA_ACTIVE_UNIT_EFFECT_SETAMMO{"SETAMMO", SQL_INT, true};
constexpr Column COLUMN_DATA_ACTIVE_UNIT_EFFECT_ADDFUEL{"ADDFUEL", SQL_INT, true};
constexpr Column COLUMN_DATA_ACTIVE_UNIT_EFFECT_ADDAMMO{"ADDAMMO", SQL_INT, true};
constexpr Column COLUMN_DATA_ACTIVE_UNIT_EFFECT_MULTIPLYFUEL{"MULTIPLYFUEL", SQL_INT, true};
constexpr Column COLUMN_DATA_ACTIVE_UNIT_EFFECT_MULTIPLYAMMO{"MULTIPLYAMMO", SQL_INT, true};
constexpr Column COLUMN_DATA_ACTIVE_UNIT_EFFECT_MAKEACTIVE{"MAKEACTIVE", SQL_BOOL, true};
constexpr Column COLUMN_DATA_ACTIVE_UNIT_EFFECT_STUNDURATION{"STUNDURATION", SQL_INT, true};
constexpr Column COLUMN_DATA_ACTIVE_UNIT_EFFECT_COCHARGEFACTOR{"COCHARGEFACTOR", SQL_INT, true};
constexpr auto TABLE_DATA_AUE_COLUMNS =
    make_array(COLUMN_DATA_ACTIVE_UNIT_EFFECT_ID, COLUMN_DATA_ACTIVE_UNIT_EFFECT_MOD_ID, COLUMN_DATA_ACTIVE_UNIT_EFFECT_NAME,
               COLUMN_DATA_ACTIVE_UNIT_EFFECT_HITPOINT, COLUMN_DATA_ACTIVE_UNIT_EFFECT_ROUNDHITPOINT, COLUMN_DATA_ACTIVE_UNIT_EFFECT_SETFUEL,
               COLUMN_DATA_ACTIVE_UNIT_EFFECT_SETAMMO, COLUMN_DATA_ACTIVE_UNIT_EFFECT_ADDFUEL, COLUMN_DATA_ACTIVE_UNIT_EFFECT_ADDAMMO,
               COLUMN_DATA_ACTIVE_UNIT_EFFECT_MULTIPLYFUEL, COLUMN_DATA_ACTIVE_UNIT_EFFECT_MULTIPLYAMMO, COLUMN_DATA_ACTIVE_UNIT_EFFECT_MAKEACTIVE,
               COLUMN_DATA_ACTIVE_UNIT_EFFECT_STUNDURATION, COLUMN_DATA_ACTIVE_UNIT_EFFECT_COCHARGEFACTOR);

constexpr std::string_view TABLE_DATA_PASSIVE_TERRAIN_EFFECT = "PASSIVE_TERRAIN_EFFECT";
constexpr Column COLUMN_DATA_PASSIVE_TERRAIN_EFFECT_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_PASSIVE_TERRAIN_EFFECT_MOD_ID{"MOD_ID", SQL_INT};
constexpr Column COLUMN_DATA_PASSIVE_TERRAIN_EFFECT_NAME{"NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_PASSIVE_TERRAIN_EFFECT_INCOME{"INCOMEMOD", SQL_INT, true};
constexpr Column COLUMN_DATA_PASSIVE_TERRAIN_EFFECT_INCOMEFLAT{"INCOMEFLATMOD", SQL_INT, true};
constexpr Column COLUMN_DATA_PASSIVE_TERRAIN_EFFECT_REPAIR{"REPAIRMOD", SQL_INT, true};
constexpr Column COLUMN_DATA_PASSIVE_TERRAIN_EFFECT_OCCLUDESVISION{"OCCLUDESVISIONMOD", SQL_BOOL, true};
constexpr Column COLUMN_DATA_PASSIVE_TERRAIN_EFFECT_VISION{"VISIONMODBOOST", SQL_INT, true};
constexpr Column COLUMN_DATA_PASSIVE_TERRAIN_EFFECT_BUILDCOST{"BUILDCOSTMOD", SQL_INT, true};
constexpr auto TABLE_DATA_PTE_COLUMNS = make_array(
    COLUMN_DATA_PASSIVE_TERRAIN_EFFECT_ID, COLUMN_DATA_PASSIVE_TERRAIN_EFFECT_MOD_ID, COLUMN_DATA_PASSIVE_TERRAIN_EFFECT_NAME,
    COLUMN_DATA_PASSIVE_TERRAIN_EFFECT_INCOME, COLUMN_DATA_PASSIVE_TERRAIN_EFFECT_INCOMEFLAT, COLUMN_DATA_PASSIVE_TERRAIN_EFFECT_REPAIR,
    COLUMN_DATA_PASSIVE_TERRAIN_EFFECT_OCCLUDESVISION, COLUMN_DATA_PASSIVE_TERRAIN_EFFECT_VISION, COLUMN_DATA_PASSIVE_TERRAIN_EFFECT_BUILDCOST);
constexpr std::string_view TABLE_DATA_PTE_BUILDLISTMOD = "PTE_BUILDLISTMOD_REFERENCE";
constexpr Column COLUMN_DATA_PTE_BUILDLISTMOD_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_PTE_BUILDLISTMOD_MOD_ID{"MOD_ID", SQL_INT};
constexpr Column COLUMN_DATA_PTE_BUILDLISTMOD_EFFECT_NAME{"EFFECT_NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_PTE_BUILDLISTMOD_UNIT{"UNITTYPE_NAME", SQL_SMALLSTRING};
constexpr auto TABLE_DATA_PTE_BUILDLISTMOD_COLUMNS = make_array(COLUMN_DATA_PTE_BUILDLISTMOD_ID, COLUMN_DATA_PTE_BUILDLISTMOD_MOD_ID,
                                                                COLUMN_DATA_PTE_BUILDLISTMOD_EFFECT_NAME, COLUMN_DATA_PTE_BUILDLISTMOD_UNIT);

constexpr std::string_view TABLE_DATA_ACTIVE_TERRAIN_EFFECT = "ACTIVE_TERRAIN_EFFECT";
constexpr Column COLUMN_DATA_ACTIVE_TERRAIN_EFFECT_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_ACTIVE_TERRAIN_EFFECT_MOD_ID{"MOD_ID", SQL_INT};
constexpr Column COLUMN_DATA_ACTIVE_TERRAIN_EFFECT_NAME{"NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_ACTIVE_TERRAIN_EFFECT_UNITSUMMONEDNAME{"UNITSUMMONEDNAME", SQL_SMALLSTRING, true};
constexpr Column COLUMN_DATA_ACTIVE_TERRAIN_EFFECT_UNITSUMMONEDDAMAGE{"UNITSUMMONEDINITIALDAMAGE", SQL_INT, true};
constexpr Column COLUMN_DATA_ACTIVE_TERRAIN_EFFECT_UNITSUMMONEDACTIVE{"UNITSUMMONEDACTIVE", SQL_BOOL, true};
constexpr auto TABLE_DATA_ATE_COLUMNS =
    make_array(COLUMN_DATA_ACTIVE_TERRAIN_EFFECT_ID, COLUMN_DATA_ACTIVE_TERRAIN_EFFECT_MOD_ID, COLUMN_DATA_ACTIVE_TERRAIN_EFFECT_NAME,
               COLUMN_DATA_ACTIVE_TERRAIN_EFFECT_UNITSUMMONEDNAME, COLUMN_DATA_ACTIVE_TERRAIN_EFFECT_UNITSUMMONEDDAMAGE,
               COLUMN_DATA_ACTIVE_TERRAIN_EFFECT_UNITSUMMONEDACTIVE);

constexpr std::string_view TABLE_DATA_PASSIVE_GLOBAL_EFFECT = "PASSIVE_GLOBAL_EFFECT";
constexpr Column COLUMN_DATA_PASSIVE_GLOBAL_EFFECT_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_PASSIVE_GLOBAL_EFFECT_MOD_ID{"MOD_ID", SQL_INT};
constexpr Column COLUMN_DATA_PASSIVE_GLOBAL_EFFECT_NAME{"NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_PASSIVE_GLOBAL_EFFECT_VARIANT{"VARIANTMOD", SQL_SMALLSTRING, true};
constexpr Column COLUMN_DATA_PASSIVE_GLOBAL_EFFECT_MOVEMENTVARIANTREPLACE{"MOVEMENTCLASSVARIANTREPLACE", SQL_SMALLSTRING, true};
constexpr Column COLUMN_DATA_PASSIVE_GLOBAL_EFFECT_MOVEMENTVARIANTOVERRIDE{"MOVEMENTCLASSVARIANTOVERRIDE", SQL_SMALLSTRING, true};
constexpr Column COLUMN_DATA_PASSIVE_GLOBAL_EFFECT_MINIMUMVISIONMOD{"MINIMUMVISIONMOD", SQL_INT, true};
constexpr auto TABLE_DATA_PGE_COLUMNS =
    make_array(COLUMN_DATA_PASSIVE_GLOBAL_EFFECT_ID, COLUMN_DATA_PASSIVE_GLOBAL_EFFECT_MOD_ID, COLUMN_DATA_PASSIVE_GLOBAL_EFFECT_NAME,
               COLUMN_DATA_PASSIVE_GLOBAL_EFFECT_VARIANT, COLUMN_DATA_PASSIVE_GLOBAL_EFFECT_MOVEMENTVARIANTREPLACE,
               COLUMN_DATA_PASSIVE_GLOBAL_EFFECT_MOVEMENTVARIANTOVERRIDE, COLUMN_DATA_PASSIVE_GLOBAL_EFFECT_MINIMUMVISIONMOD);
constexpr std::string_view TABLE_DATA_PGE_VARIANTHINTMOD = "PGE_VARIANTHINTMOD_REFERENCE";
constexpr Column COLUMN_DATA_PGE_VARIANTHINTMOD_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_PGE_VARIANTHINTMOD_MOD_ID{"MOD_ID", SQL_INT};
constexpr Column COLUMN_DATA_PGE_VARIANTHINTMOD_EFFECT_NAME{"EFFECT_NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_PGE_VARIANTHINTMOD_EFFECT_VARIANT{"VARIANT", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_PGE_VARIANTHINTMOD_HINT{"HINTMOD", SQL_INT};
constexpr auto TABLE_DATA_PGE_VARIANTHINTMOD_COLUMNS =
    make_array(COLUMN_DATA_PGE_VARIANTHINTMOD_ID, COLUMN_DATA_PGE_VARIANTHINTMOD_MOD_ID, COLUMN_DATA_PGE_VARIANTHINTMOD_EFFECT_NAME,
               COLUMN_DATA_PGE_VARIANTHINTMOD_EFFECT_VARIANT, COLUMN_DATA_PGE_VARIANTHINTMOD_HINT);

constexpr std::string_view TABLE_DATA_ACTIVE_GLOBAL_EFFECT = "ACTIVE_GLOBAL_EFFECT";
constexpr Column COLUMN_DATA_ACTIVE_GLOBAL_EFFECT_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_ACTIVE_GLOBAL_EFFECT_MOD_ID{"MOD_ID", SQL_INT};
constexpr Column COLUMN_DATA_ACTIVE_GLOBAL_EFFECT_NAME{"NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_ACTIVE_GLOBAL_EFFECT_FUND{"FUNDMOD", SQL_INT, true};
constexpr Column COLUMN_DATA_ACTIVE_GLOBAL_EFFECT_FUNDFLAT{"FUNDFLATMOD", SQL_INT, true};
constexpr Column COLUMN_DATA_ACTIVE_GLOBAL_EFFECT_POWERBAR{"POWERBARMOD", SQL_INT, true};
constexpr Column COLUMN_DATA_ACTIVE_GLOBAL_EFFECT_POWERBARPERFUNDS{"POWERBARPERFUNDS", SQL_INT, true};
constexpr Column COLUMN_DATA_ACTIVE_GLOBAL_EFFECT_MISSILECOUNT{"MISSILECOUNT", SQL_INT, true};
constexpr Column COLUMN_DATA_ACTIVE_GLOBAL_EFFECT_MISSILEDAMAGE{"MISSILEDAMAGE", SQL_INT, true};
constexpr Column COLUMN_DATA_ACTIVE_GLOBAL_EFFECT_MISSILEAREAOFEFFECT{"MISSILEAREAOFEFFECT", SQL_INT, true};
constexpr Column COLUMN_DATA_ACTIVE_GLOBAL_EFFECT_MISSILESTUNDURATION{"MISSILESTUNDURATION", SQL_INT, true};
constexpr Column COLUMN_DATA_ACTIVE_GLOBAL_EFFECT_COCHARGEFACTOR{"COCHARGEFACTOR", SQL_INT, true};
constexpr auto TABLE_DATA_AGE_COLUMNS =
    make_array(COLUMN_DATA_ACTIVE_GLOBAL_EFFECT_ID, COLUMN_DATA_ACTIVE_GLOBAL_EFFECT_MOD_ID, COLUMN_DATA_ACTIVE_GLOBAL_EFFECT_NAME,
               COLUMN_DATA_ACTIVE_GLOBAL_EFFECT_FUND, COLUMN_DATA_ACTIVE_GLOBAL_EFFECT_FUNDFLAT, COLUMN_DATA_ACTIVE_GLOBAL_EFFECT_POWERBAR,
               COLUMN_DATA_ACTIVE_GLOBAL_EFFECT_POWERBARPERFUNDS, COLUMN_DATA_ACTIVE_GLOBAL_EFFECT_MISSILECOUNT,
               COLUMN_DATA_ACTIVE_GLOBAL_EFFECT_MISSILEDAMAGE, COLUMN_DATA_ACTIVE_GLOBAL_EFFECT_MISSILEAREAOFEFFECT,
               COLUMN_DATA_ACTIVE_GLOBAL_EFFECT_MISSILESTUNDURATION, COLUMN_DATA_ACTIVE_GLOBAL_EFFECT_COCHARGEFACTOR);
constexpr std::string_view TABLE_DATA_AGE_MISSILETARGETMETHOD = "AGE_MISSILETARGETMETHOD_REFERENCE";
constexpr Column COLUMN_DATA_AGE_MISSILETARGETMETHOD_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_AGE_MISSILETARGETMETHOD_MOD_ID{"MOD_ID", SQL_INT};
constexpr Column COLUMN_DATA_AGE_MISSILETARGETMETHOD_EFFECT_NAME{"EFFECT_NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_AGE_MISSILETARGETMETHOD_EFFECT_TARGET_METHOD{"TARGETMETHOD", SQL_SMALLSTRING};
constexpr auto TABLE_DATA_AGE_MISSILETARGETMETHOD_COLUMNS =
    make_array(COLUMN_DATA_AGE_MISSILETARGETMETHOD_ID, COLUMN_DATA_AGE_MISSILETARGETMETHOD_MOD_ID, COLUMN_DATA_AGE_MISSILETARGETMETHOD_EFFECT_NAME,
               COLUMN_DATA_AGE_MISSILETARGETMETHOD_EFFECT_TARGET_METHOD);

constexpr std::string_view TABLE_DATA_DEFAULT_GAME_SETTINGS = "DEFAULT_GAME_SETTINGS";
constexpr Column COLUMN_DATA_SETTINGS_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_SETTINGS_MOD_ID{"MOD_ID", SQL_INT};
constexpr Column COLUMN_DATA_SETTINGS_NAME{"NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_SETTINGS_FOG{"FOGOFWAR", SQL_BOOL, true};
constexpr Column COLUMN_DATA_SETTINGS_POWERS{"COPOWERS", SQL_BOOL, true};
constexpr Column COLUMN_DATA_SETTINGS_TEAMS{"TEAMS", SQL_BOOL, true};
constexpr Column COLUMN_DATA_SETTINGS_STARTINGFUNDS{"STARTINGFUNDS", SQL_INT, true};
constexpr Column COLUMN_DATA_SETTINGS_INCOMEMULTIPLIER{"INCOMEMULTIPLIER", SQL_INT, true};
constexpr Column COLUMN_DATA_SETTINGS_UNITLIMIT{"UNITLIMIT", SQL_INT, true};
constexpr Column COLUMN_DATA_SETTINGS_CAPTURELIMIT{"CAPTURELIMIT", SQL_INT, true};
constexpr Column COLUMN_DATA_SETTINGS_DAYLIMIT{"DAYLIMIT", SQL_INT, true};
constexpr Column COLUMN_DATA_SETTINGS_COMETERSIZE{"COMETERSIZE", SQL_INT, true};
constexpr Column COLUMN_DATA_SETTINGS_COMETERMULTIPLIER{"COMETERMULTIPLIER", SQL_INT, true};
constexpr auto TABLE_DATA_DEFAULT_GAME_SETTINGS_COLUMNS = make_array(
    COLUMN_DATA_SETTINGS_ID, COLUMN_DATA_SETTINGS_MOD_ID, COLUMN_DATA_SETTINGS_NAME, COLUMN_DATA_SETTINGS_FOG, COLUMN_DATA_SETTINGS_POWERS,
    COLUMN_DATA_SETTINGS_TEAMS, COLUMN_DATA_SETTINGS_STARTINGFUNDS, COLUMN_DATA_SETTINGS_INCOMEMULTIPLIER, COLUMN_DATA_SETTINGS_UNITLIMIT,
    COLUMN_DATA_SETTINGS_CAPTURELIMIT, COLUMN_DATA_SETTINGS_DAYLIMIT, COLUMN_DATA_SETTINGS_COMETERSIZE, COLUMN_DATA_SETTINGS_COMETERMULTIPLIER);
constexpr std::string_view TABLE_DATA_DEFAULTSETTINGS_VARIANT = "DEFAULTSETTINGS_VARIANT_REFERENCE";
constexpr Column COLUMN_DATA_SETTINGS_VARIANT_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_SETTINGS_VARIANT_MOD_ID{"MOD_ID", SQL_INT};
constexpr Column COLUMN_DATA_SETTINGS_VARIANT_SETTING{"SETTING_NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_SETTINGS_VARIANT_VARIANT{"VARIANT", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_SETTINGS_VARIANT_VALUE{"VALUE", SQL_INT};
constexpr auto TABLE_DATA_SETTINGS_VARIANT_COLUMNS =
    make_array(COLUMN_DATA_SETTINGS_VARIANT_ID, COLUMN_DATA_SETTINGS_VARIANT_MOD_ID, COLUMN_DATA_SETTINGS_VARIANT_SETTING,
               COLUMN_DATA_SETTINGS_VARIANT_VARIANT, COLUMN_DATA_SETTINGS_VARIANT_VALUE);

constexpr std::string_view TABLE_DATA_CONFIG = "CONFIG";
constexpr Column COLUMN_DATA_CONFIG_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_CONFIG_MOD_ID{"MOD_ID", SQL_INT};
constexpr Column COLUMN_DATA_CONFIG_MINTERRAINSTARS{"MINTERRAINSTARS", SQL_INT, true};
constexpr Column COLUMN_DATA_CONFIG_UNLIMITEDUNLOAD{"UNLIMITEDUNLOAD", SQL_BOOL, true};
constexpr Column COLUMN_DATA_CONFIG_TERRAINDEFENSESCALES{"TERRAINDEFENSESCALESWITHHITPOINTS", SQL_BOOL, true};
constexpr Column COLUMN_DATA_CONFIG_TERRAINFIREPOWERSCALES{"TERRAINFIREPOWERSCALESWITHHITPOINTS", SQL_BOOL, true};
constexpr auto TABLE_DATA_CONFIG_COLUMNS =
    make_array(COLUMN_DATA_CONFIG_ID, COLUMN_DATA_CONFIG_MOD_ID, COLUMN_DATA_CONFIG_MINTERRAINSTARS, COLUMN_DATA_CONFIG_UNLIMITEDUNLOAD,
               COLUMN_DATA_CONFIG_TERRAINDEFENSESCALES, COLUMN_DATA_CONFIG_TERRAINFIREPOWERSCALES);

constexpr std::string_view TABLE_DATA_MAP_DEFINITION = "MAP_DEFINITION";
constexpr Column COLUMN_DATA_MAP_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_MAP_NAME{"NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_MAP_VERSION{"VERSION", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_MAP_EXPIRED{"EXPIRED", SQL_DATETIME, true};
constexpr Column COLUMN_DATA_MAP_DESCRIPTION{"DESCRIPTION", SQL_LARGESTRING, true};
constexpr Column COLUMN_DATA_MAP_MOD_NAME{"MOD_NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_MAP_MOD_VERSION{"MOD_VERSION", SQL_SMALLSTRING, true};
constexpr auto TABLE_DATA_MAP_DEFINITION_COLUMNS =
    make_array(COLUMN_DATA_MAP_ID, COLUMN_DATA_MAP_NAME, COLUMN_DATA_MAP_VERSION, COLUMN_DATA_MAP_EXPIRED, COLUMN_DATA_MAP_DESCRIPTION,
               COLUMN_DATA_MAP_MOD_NAME, COLUMN_DATA_MAP_MOD_VERSION);
constexpr std::string_view TABLE_DATA_MAP_PLAYERSLOT = "MAP_PLAYERSLOT";
constexpr Column COLUMN_DATA_MAP_PLAYERSLOT_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_MAP_PLAYERSLOT_MAP_ID{"MAP_ID", SQL_INT};
constexpr Column COLUMN_DATA_MAP_PLAYERSLOT_PLAYERSLOT{"PLAYERSLOT", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_MAP_PLAYERSLOT_ORDER{"ORDER", SQL_INT};
constexpr auto TABLE_DATA_MAP_PLAYERSLOT_COLUMNS = make_array(COLUMN_DATA_MAP_PLAYERSLOT_ID, COLUMN_DATA_MAP_PLAYERSLOT_MAP_ID,
                                                              COLUMN_DATA_MAP_PLAYERSLOT_PLAYERSLOT, COLUMN_DATA_MAP_PLAYERSLOT_ORDER);
constexpr std::string_view TABLE_DATA_MAP_INITIAL_TERRAIN = "MAP_INITIAL_TERRAIN";
constexpr Column COLUMN_DATA_MAP_TERRAIN_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_MAP_TERRAIN_MAP_ID{"MAP_ID", SQL_INT};
constexpr Column COLUMN_DATA_MAP_TERRAIN_NAME{"NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_MAP_TERRAIN_X{"X", SQL_INT};
constexpr Column COLUMN_DATA_MAP_TERRAIN_Y{"Y", SQL_INT};
constexpr Column COLUMN_DATA_MAP_TERRAIN_ORIENTATION{"ORIENTATION", SQL_INT, true};
constexpr Column COLUMN_DATA_MAP_TERRAIN_PLAYER_SLOT{"PLAYER_SLOT", SQL_SMALLSTRING, true};
constexpr Column COLUMN_DATA_MAP_TERRAIN_HITPOINTS{"STARTING_HITPOINTS", SQL_INT, true};
constexpr Column COLUMN_DATA_MAP_TERRAIN_CAPTURE_POINTS{"STARTING_CAPTURE_POINTS", SQL_INT, true};
constexpr auto TABLE_DATA_MAP_TERRAIN_COLUMNS =
    make_array(COLUMN_DATA_MAP_TERRAIN_ID, COLUMN_DATA_MAP_TERRAIN_MAP_ID, COLUMN_DATA_MAP_TERRAIN_NAME, COLUMN_DATA_MAP_TERRAIN_X,
               COLUMN_DATA_MAP_TERRAIN_Y, COLUMN_DATA_MAP_TERRAIN_ORIENTATION, COLUMN_DATA_MAP_TERRAIN_PLAYER_SLOT, COLUMN_DATA_MAP_TERRAIN_HITPOINTS,
               COLUMN_DATA_MAP_TERRAIN_CAPTURE_POINTS);
constexpr std::string_view TABLE_DATA_MAP_INITIAL_UNIT = "MAP_INITIAL_UNIT";
constexpr Column COLUMN_DATA_MAP_UNIT_ID{"ID", SQL_INT, false, true};
constexpr Column COLUMN_DATA_MAP_UNIT_MAP_ID{"MAP_ID", SQL_INT};
constexpr Column COLUMN_DATA_MAP_UNIT_NAME{"NAME", SQL_SMALLSTRING};
constexpr Column COLUMN_DATA_MAP_UNIT_X{"X", SQL_INT};
constexpr Column COLUMN_DATA_MAP_UNIT_Y{"Y", SQL_INT};
constexpr Column COLUMN_DATA_MAP_UNIT_PLAYER_SLOT{"PLAYER_SLOT", SQL_SMALLSTRING, true};
constexpr Column COLUMN_DATA_MAP_UNIT_HITPOINTS{"STARTING_HITPOINTS", SQL_INT, true};
constexpr Column COLUMN_DATA_MAP_UNIT_AMMO{"STARTING_AMMO", SQL_INT, true};
constexpr Column COLUMN_DATA_MAP_UNIT_FUEL{"STARTING_FUEL", SQL_INT, true};
constexpr Column COLUMN_DATA_MAP_UNIT_STUNNED{"STARTING_STUNNED", SQL_INT, true};
constexpr Column COLUMN_DATA_MAP_UNIT_STEALTHED{"STARTING_STEALTHED", SQL_BOOL, true};
constexpr Column COLUMN_DATA_MAP_UNIT_LUCK{"STARTING_LUCK", SQL_DOUBLE, true};
constexpr Column COLUMN_DATA_MAP_UNIT_TRANSPORTED_BY{"TRANSPORTED_BY", SQL_INT, true};
constexpr auto TABLE_DATA_MAP_UNIT_COLUMNS =
    make_array(COLUMN_DATA_MAP_UNIT_ID, COLUMN_DATA_MAP_UNIT_MAP_ID, COLUMN_DATA_MAP_UNIT_NAME, COLUMN_DATA_MAP_UNIT_X, COLUMN_DATA_MAP_UNIT_Y,
               COLUMN_DATA_MAP_UNIT_PLAYER_SLOT, COLUMN_DATA_MAP_UNIT_HITPOINTS, COLUMN_DATA_MAP_UNIT_AMMO, COLUMN_DATA_MAP_UNIT_FUEL,
               COLUMN_DATA_MAP_UNIT_STUNNED, COLUMN_DATA_MAP_UNIT_STEALTHED, COLUMN_DATA_MAP_UNIT_LUCK, COLUMN_DATA_MAP_UNIT_TRANSPORTED_BY);
DBErrorCode buildDatabase();
}  // namespace db::v0_0_1