set(Boost_USE_STATIC_LIBS ON)
set(Boost_USE_MULTITHREADED ON)
set(Boost_USE_STATIC_RUNTIME OFF)
find_package(Boost 1.84.0 COMPONENTS system json)
#find_package(OpenSSL)
add_compile_options(-Wall -Werror -pedantic-errors -std=c++26 -fconcepts-diagnostics-depth=2)
include_directories(../include/)
if(Boost_FOUND)
  include_directories(${Boost_INCLUDE_DIRS})
  add_executable(Server Archive.cpp Main.cpp Properties.cpp ResourcePacks.cpp RestFunctions.cpp RestServer.cpp SQLUtil.cpp StateLookup.cpp db/Data.cpp)
  target_link_libraries(Server ${Boost_LIBRARIES} ssl crypto dl)
endif()
